Attempting to connect to postgres database
Could not connect to the database
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

2025-02-26 05:16:18,210 - root - DEBUG - Attempting to connect to postgres database
2025-02-26 05:16:18,267 - root - INFO - Could not connect to the database
2025-02-26 05:16:18,268 - root - ERROR - connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

2025-02-26 05:16:56,955 - root - DEBUG - Attempting to connect to postgres database
2025-02-26 05:16:57,003 - root - INFO - Could not connect to the database
2025-02-26 05:16:57,003 - root - ERROR - connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

2025-02-26 05:23:43,644 - root - INFO - Could not connect to the database
2025-02-26 05:23:43,645 - root - ERROR - connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

2025-02-26 05:24:21,585 - root - ERROR - connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

2025-02-26 05:24:41,816 - root - DEBUG - Attempting to connect to postgres database
2025-02-26 05:24:41,864 - root - INFO - Could not connect to the database
2025-02-26 05:24:41,864 - root - ERROR - connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

2025-02-26 05:28:27,762 - root - DEBUG - Attempting to connect to postgres database
2025-02-26 05:28:27,802 - root - INFO - Could not connect to the database
2025-02-26 05:28:27,805 - root - ERROR - connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

2025-02-26 05:33:37,328 - root - DEBUG - Attempting to connect to postgres database
2025-02-26 05:36:34,297 - root - DEBUG - Attempting to connect to postgres database
2025-02-26 05:36:34,338 - root - INFO - Database connected successfully, cursor was obtained!
2025-02-26 05:36:57,846 - root - DEBUG - Attempting to connect to postgres database
2025-02-26 05:36:57,869 - root - INFO - Database connected successfully, cursor was obtained!
2025-02-26 05:38:04,189 - root - DEBUG - Attempting to connect to postgres database
2025-02-26 05:38:04,227 - root - INFO - Database connected successfully, cursor was obtained!
2025-02-26 05:41:49,292 - root - DEBUG - Attempting to connect to postgres database
2025-02-26 05:41:49,333 - root - INFO - Database connected successfully, cursor was obtained!
2025-02-28 11:19:24,520 - root - DEBUG - Attempting to connect to postgres database
2025-02-28 11:19:24,563 - root - INFO - Database connected successfully, cursor was obtained!
2025-02-28 11:44:13,373 - root - DEBUG - Attempting to connect to postgres database
2025-02-28 11:44:13,411 - root - INFO - Database connected successfully, cursor was obtained!
2025-02-28 11:44:13,484 - root - INFO - Database Created!
2025-02-28 12:07:33,409 - root - DEBUG - Attempting to connect to postgres database
2025-02-28 12:07:33,462 - root - INFO - Could not connect to the database
2025-02-28 12:07:33,462 - root - ERROR - connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "popstgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "popstgres"

2025-02-28 12:08:02,935 - root - DEBUG - Attempting to connect to postgres database
2025-02-28 12:08:02,959 - root - INFO - Database connected successfully, cursor was obtained!
2025-02-28 12:08:02,960 - root - INFO - Could not connect to the database
2025-02-28 12:08:02,960 - root - ERROR - database "postgres" already exists

2025-02-28 12:08:47,610 - root - DEBUG - Attempting to connect to postgres database
2025-02-28 12:08:47,635 - root - INFO - Database connected successfully, cursor was obtained!
2025-02-28 12:08:47,638 - root - ERROR - database "postgres" already exists

2025-02-28 12:10:09,818 - root - DEBUG - Attempting to connect to postgres database
2025-02-28 12:10:09,845 - root - INFO - Database connected successfully, cursor was obtained!
2025-02-28 12:10:09,850 - root - ERROR - database "retail_db" already exists

2025-02-28 12:53:23,420 - root - DEBUG - Attempting to connect to postgres database
2025-02-28 12:53:23,448 - root - INFO - Database connected successfully, cursor was obtained!
2025-02-28 12:53:23,450 - root - WARNING - Database already exists
2025-02-28 13:07:45,881 - root - DEBUG - Attempting to connect to postgres database
2025-02-28 13:07:45,907 - root - INFO - Database connected successfully, cursor was obtained!
2025-02-28 13:07:45,908 - root - WARNING - Database already exists
2025-02-28 13:07:45,916 - root - DEBUG - Database connection closed
2025-02-28 13:10:05,716 - root - DEBUG - Attempting to connect to postgres database
2025-02-28 13:10:05,761 - root - INFO - Database connected successfully, cursor was obtained!
2025-02-28 13:10:05,763 - root - ERROR - syntax error at or near "'sexy'"
LINE 1: CREATE DATABASE 'sexy';
                        ^

2025-02-28 13:10:05,764 - root - DEBUG - Database connection closed
2025-02-28 13:14:37,692 - root - DEBUG - Attempting to connect to postgres database
2025-02-28 13:14:37,753 - root - INFO - Database connected successfully, cursor was obtained!
2025-02-28 13:14:37,757 - root - ERROR - Database connection failed: syntax error at or near "("
LINE 1: CREATE DATABASE Identifier('sexy')
                                  ^

2025-02-28 13:14:37,758 - root - DEBUG - Database connection closed
2025-02-28 13:16:13,047 - root - DEBUG - Attempting to connect to postgres database
2025-02-28 13:16:13,076 - root - INFO - Database connected successfully, cursor was obtained!
2025-02-28 13:16:13,147 - root - INFO - Database Created!
2025-02-28 13:16:13,149 - root - DEBUG - Database connection closed
2025-02-28 13:27:11,978 - root - DEBUG - Attempting to connect to postgres database
2025-02-28 13:27:12,014 - root - INFO - Database connected successfully, cursor was obtained!
2025-02-28 13:27:12,016 - root - ERROR - Database connection failed: syntax error at or near "{"
LINE 1: SELECT 1 FROM pg_database where datname = {};
                                                  ^

2025-02-28 13:27:12,017 - root - DEBUG - Database connection closed
2025-02-28 13:27:25,397 - root - DEBUG - Attempting to connect to postgres database
2025-02-28 13:27:25,427 - root - INFO - Database connected successfully, cursor was obtained!
2025-02-28 13:27:25,430 - root - WARNING - Database already exists
2025-02-28 13:27:25,432 - root - DEBUG - Database connection closed
2025-03-02 03:24:49,829 - root - DEBUG - Attempting to connect to postgres database
2025-03-02 03:24:49,864 - root - INFO - Database connected successfully, cursor was obtained!
2025-03-02 03:24:49,865 - root - WARNING - Database already exists
2025-03-02 03:24:49,866 - root - DEBUG - Database connection closed
2025-03-02 03:44:54,034 - root - DEBUG - Attempting to connect to postgres database
2025-03-02 03:44:54,065 - root - INFO - Database connected successfully, cursor was obtained!
2025-03-02 03:44:54,066 - root - WARNING - Database already exists
2025-03-02 03:44:54,067 - root - DEBUG - Database connection closed
2025-03-02 03:45:25,506 - root - DEBUG - Attempting to connect to postgres database
2025-03-02 03:45:25,544 - root - INFO - Database connected successfully, cursor was obtained!
2025-03-02 03:45:25,547 - root - WARNING - Database already exists
2025-03-02 03:45:25,549 - root - DEBUG - Database connection closed
2025-03-02 03:46:56,351 - root - DEBUG - Attempting to connect to postgres database
2025-03-02 03:46:56,386 - root - INFO - Database connected successfully, cursor was obtained!
2025-03-02 03:46:56,388 - root - WARNING - Database already exists
2025-03-02 03:46:56,392 - root - DEBUG - Database connection closed
2025-03-02 03:46:56,392 - root - DEBUG - Attempting to connect to retail_db...
2025-03-02 03:46:56,419 - root - INFO - Database connected successfully!
2025-03-02 04:46:25,495 - root - DEBUG - Attempting to connect to postgres database
2025-03-02 04:46:25,520 - root - INFO - Database connected successfully, cursor was obtained!
2025-03-02 04:46:25,525 - root - WARNING - Database already exists
2025-03-02 04:46:25,525 - root - DEBUG - Database connection closed
2025-03-02 04:46:25,526 - root - DEBUG - Attempting to connect to retail_db...
2025-03-02 04:46:25,549 - root - INFO - retail_db connected successfully!
2025-03-02 04:46:25,549 - root - DEBUG - Executing tables creation query
2025-03-02 04:46:25,550 - root - ERROR - Tables creation failed syntax error at or near "FORGEIN"
LINE 25:                 FORGEIN KEY (InvoiceNO) REFERENCES invoice(I...
                         ^

2025-03-02 04:47:34,864 - root - DEBUG - Attempting to connect to postgres database
2025-03-02 04:47:34,892 - root - INFO - Database connected successfully, cursor was obtained!
2025-03-02 04:47:34,894 - root - WARNING - Database already exists
2025-03-02 04:47:34,895 - root - DEBUG - Database connection closed
2025-03-02 04:47:34,899 - root - DEBUG - Attempting to connect to retail_db...
2025-03-02 04:47:34,921 - root - INFO - retail_db connected successfully!
2025-03-02 04:47:34,921 - root - DEBUG - Executing tables creation query
2025-03-02 04:47:34,923 - root - ERROR - Tables creation failed syntax error at or near "FORGEIN"
LINE 25:                 FORGEIN KEY (InvoiceNO) REFERENCES invoice(I...
                         ^

2025-03-02 04:48:39,187 - root - DEBUG - Attempting to connect to postgres database
2025-03-02 04:48:39,214 - root - INFO - Database connected successfully, cursor was obtained!
2025-03-02 04:48:39,216 - root - WARNING - Database already exists
2025-03-02 04:48:39,218 - root - DEBUG - Database connection closed
2025-03-02 04:48:39,218 - root - DEBUG - Attempting to connect to retail_db...
2025-03-02 04:48:39,242 - root - INFO - retail_db connected successfully!
2025-03-02 04:48:39,243 - root - DEBUG - Executing tables creation query
2025-03-02 04:48:39,244 - root - ERROR - Tables creation failed syntax error at or near "FOREIGN"
LINE 25:                 FOREIGN KEY (InvoiceNO) REFERENCES invoice(I...
                         ^

2025-03-02 04:49:41,493 - root - DEBUG - Attempting to connect to postgres database
2025-03-02 04:49:41,534 - root - INFO - Database connected successfully, cursor was obtained!
2025-03-02 04:49:41,535 - root - WARNING - Database already exists
2025-03-02 04:49:41,537 - root - DEBUG - Database connection closed
2025-03-02 04:49:41,538 - root - DEBUG - Attempting to connect to retail_db...
2025-03-02 04:49:41,575 - root - INFO - retail_db connected successfully!
2025-03-02 04:49:41,575 - root - DEBUG - Executing tables creation query
2025-03-02 04:49:41,576 - root - ERROR - Tables creation failed syntax error at or near "FOREIGN"
LINE 25:                 FOREIGN KEY (InvoiceNO) REFERENCES invoice(I...
                         ^

2025-03-02 04:51:25,374 - root - DEBUG - Attempting to connect to postgres database
2025-03-02 04:51:25,412 - root - INFO - Database connected successfully, cursor was obtained!
2025-03-02 04:51:25,417 - root - WARNING - Database already exists
2025-03-02 04:51:25,419 - root - DEBUG - Database connection closed
2025-03-02 04:51:25,420 - root - DEBUG - Attempting to connect to retail_db...
2025-03-02 04:51:25,449 - root - INFO - retail_db connected successfully!
2025-03-02 04:51:25,449 - root - DEBUG - Executing tables creation query
2025-03-02 04:51:25,465 - root - ERROR - Tables creation failed relation "customers" does not exist

2025-03-02 04:51:56,784 - root - DEBUG - Attempting to connect to postgres database
2025-03-02 04:51:56,813 - root - INFO - Database connected successfully, cursor was obtained!
2025-03-02 04:51:56,817 - root - WARNING - Database already exists
2025-03-02 04:51:56,817 - root - DEBUG - Database connection closed
2025-03-02 04:51:56,818 - root - DEBUG - Attempting to connect to retail_db...
2025-03-02 04:51:56,843 - root - INFO - retail_db connected successfully!
2025-03-02 04:51:56,844 - root - DEBUG - Executing tables creation query
2025-03-02 04:51:56,868 - root - INFO - Tables created successfully!
2025-03-02 05:17:19,050 - root - DEBUG - Attempting to connect to postgres database
2025-03-02 05:17:19,076 - root - INFO - Database connected successfully, cursor was obtained!
2025-03-02 05:17:19,077 - root - WARNING - Database already exists
2025-03-02 05:17:19,078 - root - DEBUG - Database connection closed
2025-03-02 05:17:19,078 - root - DEBUG - Attempting to connect to retail_db...
2025-03-02 05:17:19,111 - root - INFO - retail_db connected successfully!
2025-03-02 05:17:19,114 - root - DEBUG - Executing tables creation query
2025-03-02 05:17:19,115 - root - INFO - Tables created successfully!
2025-03-02 06:42:20,517 - root - DEBUG - Attempting to connect to postgres ...
2025-03-02 06:42:20,546 - root - DEBUG - Connected successfully to postgres
2025-03-02 06:43:36,012 - root - DEBUG - Attempting to connect to postgres ...
2025-03-02 06:43:36,038 - root - DEBUG - Connected successfully to postgres
2025-03-02 06:44:23,224 - root - DEBUG - Attempting to connect to postgres ...
2025-03-02 06:44:23,250 - root - DEBUG - Connected successfully to postgres
2025-03-02 06:44:23,251 - root - ERROR - Database retail_db already exists
2025-03-02 06:49:39,147 - root - DEBUG - Attempting to connect to postgres ...
2025-03-02 06:49:39,174 - root - DEBUG - Connected successfully to postgres
2025-03-02 06:49:39,176 - root - ERROR - Database retail_db already exists
2025-03-02 06:49:39,177 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-02 06:49:39,202 - root - DEBUG - Connected successfully to retail_db
2025-03-02 06:49:39,203 - root - DEBUG - Executing tables creation query
2025-03-02 06:49:39,203 - root - INFO - Tables created successfully!
2025-03-02 06:49:39,204 - root - DEBUG - Database conncetion closed
2025-03-04 02:46:19,752 - root - INFO - Dataset read
2025-03-04 02:47:13,922 - root - INFO - Dataset read
2025-03-04 02:47:14,446 - root - INFO - corrupted rows removed from the dataset
2025-03-04 02:47:15,647 - root - INFO - Duplicated rows removed from the dataset
2025-03-04 02:47:16,153 - root - INFO - Data types corrected
2025-03-04 04:41:51,489 - root - DEBUG - Attempting to connect to postgres ...
2025-03-04 04:41:51,523 - root - DEBUG - Connected successfully to postgres
2025-03-04 04:43:16,396 - root - DEBUG - Attempting to connect to postgres ...
2025-03-04 04:43:16,422 - root - DEBUG - Connected successfully to postgres
2025-03-04 04:43:52,504 - root - DEBUG - Attempting to connect to postgres ...
2025-03-04 04:43:52,531 - root - DEBUG - Connected successfully to postgres
2025-03-04 04:43:52,769 - root - INFO - Database retail_db created!
2025-03-04 04:43:52,769 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-04 04:43:52,791 - root - DEBUG - Connected successfully to retail_db
2025-03-04 04:43:52,791 - root - DEBUG - Executing tables creation query
2025-03-04 04:43:52,823 - root - INFO - Tables created successfully!
2025-03-04 04:43:52,823 - root - DEBUG - Database conncetion closed
2025-03-04 06:24:05,475 - root - DEBUG - Attempting to connect to postgres ...
2025-03-04 06:24:05,498 - root - DEBUG - Connected successfully to postgres
2025-03-04 06:24:05,543 - root - INFO - Database retail_db created!
2025-03-04 06:24:05,548 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-04 06:24:05,581 - root - DEBUG - Connected successfully to retail_db
2025-03-04 06:24:05,581 - root - DEBUG - Executing tables creation query
2025-03-04 06:24:05,609 - root - INFO - Tables created successfully!
2025-03-04 06:24:05,612 - root - DEBUG - Database conncetion closed
2025-03-05 09:24:59,640 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:24:59,696 - root - ERROR - Connection error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

2025-03-05 09:24:59,696 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:24:59,742 - root - ERROR - Connection error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

2025-03-05 09:25:22,681 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:25:22,708 - root - DEBUG - Connected successfully to postgres
2025-03-05 09:25:22,709 - root - ERROR - Database retail_db already exists
2025-03-05 09:25:22,712 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:25:22,731 - root - DEBUG - Connected successfully to retail_db
2025-03-05 09:25:22,732 - root - DEBUG - Executing tables creation query
2025-03-05 09:25:22,734 - root - INFO - Tables created successfully!
2025-03-05 09:25:22,734 - root - DEBUG - Database conncetion closed
2025-03-05 09:29:06,976 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:29:07,047 - root - ERROR - Connection error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

2025-03-05 09:29:07,047 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:29:07,099 - root - ERROR - Connection error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

2025-03-05 09:29:07,100 - root - DEBUG - Database conncetion closed
2025-03-05 09:29:24,666 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:29:24,693 - root - DEBUG - Connected successfully to postgres
2025-03-05 09:29:24,697 - root - ERROR - Database retail_db already exists
2025-03-05 09:29:24,697 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:29:24,721 - root - DEBUG - Connected successfully to retail_db
2025-03-05 09:29:24,721 - root - DEBUG - Executing tables creation query
2025-03-05 09:29:24,724 - root - INFO - Tables created successfully!
2025-03-05 09:29:24,725 - root - DEBUG - Database conncetion closed
2025-03-05 09:36:57,712 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:36:57,731 - root - DEBUG - Connected successfully to postgres
2025-03-05 09:36:57,733 - root - ERROR - Database retail_db already exists
2025-03-05 09:36:57,733 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:36:57,752 - root - DEBUG - Connected successfully to retail_db
2025-03-05 09:36:57,752 - root - DEBUG - Executing tables creation query
2025-03-05 09:36:57,753 - root - INFO - Tables created successfully!
2025-03-05 09:36:57,753 - root - DEBUG - Database conncetion closed
2025-03-05 09:36:58,736 - root - INFO - Dataset read
2025-03-05 09:36:59,023 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-05 09:36:59,082 - root - INFO - Identified 1454 corrupted rows.
2025-03-05 09:36:59,210 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-05 09:37:00,053 - root - INFO - Identified 5268 duplicate rows.
2025-03-05 09:37:00,055 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-05 09:37:00,547 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-05 09:37:00,630 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-05 09:37:00,648 - root - INFO - Database connected successfully
2025-03-05 09:40:20,735 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:40:20,759 - root - DEBUG - Connected successfully to postgres
2025-03-05 09:40:20,760 - root - ERROR - Database retail_db already exists
2025-03-05 09:40:20,762 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:40:20,786 - root - DEBUG - Connected successfully to retail_db
2025-03-05 09:40:20,786 - root - DEBUG - Executing tables creation query
2025-03-05 09:40:20,787 - root - INFO - Tables created successfully!
2025-03-05 09:40:20,787 - root - DEBUG - Database conncetion closed
2025-03-05 09:40:21,748 - root - INFO - Dataset read
2025-03-05 09:40:22,032 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-05 09:40:22,094 - root - INFO - Identified 1454 corrupted rows.
2025-03-05 09:40:22,201 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-05 09:40:23,007 - root - INFO - Identified 5268 duplicate rows.
2025-03-05 09:40:23,008 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-05 09:40:23,510 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-05 09:40:23,573 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-05 09:40:23,573 - root - DEBUG - Attempting to connect to retail_db.
2025-03-05 09:40:23,574 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:40:23,591 - root - ERROR - Connection error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  database "{'dbname': 'retail_db', 'user': 'postgres', 'password': '123', " does not exist

2025-03-05 09:41:05,690 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:41:05,723 - root - DEBUG - Connected successfully to postgres
2025-03-05 09:41:05,724 - root - ERROR - Database retail_db already exists
2025-03-05 09:41:05,724 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:41:05,760 - root - DEBUG - Connected successfully to retail_db
2025-03-05 09:41:05,761 - root - DEBUG - Executing tables creation query
2025-03-05 09:41:05,766 - root - INFO - Tables created successfully!
2025-03-05 09:41:05,769 - root - DEBUG - Database conncetion closed
2025-03-05 09:41:06,886 - root - INFO - Dataset read
2025-03-05 09:41:07,208 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-05 09:41:07,270 - root - INFO - Identified 1454 corrupted rows.
2025-03-05 09:41:07,371 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-05 09:41:08,203 - root - INFO - Identified 5268 duplicate rows.
2025-03-05 09:41:08,203 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-05 09:41:08,683 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-05 09:41:08,749 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-05 09:41:08,749 - root - DEBUG - Attempting to connect to retail_db.
2025-03-05 09:42:25,455 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:42:25,479 - root - DEBUG - Connected successfully to postgres
2025-03-05 09:42:25,481 - root - ERROR - Database retail_db already exists
2025-03-05 09:42:25,481 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:42:25,520 - root - DEBUG - Connected successfully to retail_db
2025-03-05 09:42:25,520 - root - DEBUG - Executing tables creation query
2025-03-05 09:42:25,522 - root - INFO - Tables created successfully!
2025-03-05 09:42:25,522 - root - DEBUG - Database conncetion closed
2025-03-05 09:42:26,724 - root - INFO - Dataset read
2025-03-05 09:42:27,041 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-05 09:42:27,114 - root - INFO - Identified 1454 corrupted rows.
2025-03-05 09:42:27,264 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-05 09:42:28,279 - root - INFO - Identified 5268 duplicate rows.
2025-03-05 09:42:28,280 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-05 09:42:28,802 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-05 09:42:28,878 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-05 09:42:28,878 - root - DEBUG - Attempting to connect to retail_db.
2025-03-05 09:43:36,026 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:43:36,049 - root - DEBUG - Connected successfully to postgres
2025-03-05 09:43:36,053 - root - ERROR - Database retail_db already exists
2025-03-05 09:43:36,053 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:43:36,078 - root - DEBUG - Connected successfully to retail_db
2025-03-05 09:43:36,078 - root - DEBUG - Executing tables creation query
2025-03-05 09:43:36,080 - root - INFO - Tables created successfully!
2025-03-05 09:43:36,080 - root - DEBUG - Database conncetion closed
2025-03-05 09:43:37,167 - root - INFO - Dataset read
2025-03-05 09:43:37,453 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-05 09:43:37,529 - root - INFO - Identified 1454 corrupted rows.
2025-03-05 09:43:37,643 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-05 09:43:38,473 - root - INFO - Identified 5268 duplicate rows.
2025-03-05 09:43:38,473 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-05 09:43:38,951 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-05 09:43:39,017 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-05 09:43:39,017 - root - DEBUG - Attempting to connect to retail_db.
2025-03-05 09:43:39,017 - root - DEBUG - Attempting to connect to retail_db ...
2025-03-05 09:43:39,037 - root - DEBUG - Connected successfully to retail_db
2025-03-05 09:44:25,652 - root - DEBUG - Attempting to connect to retail_db
2025-03-05 09:44:25,673 - root - DEBUG - Connected successfully to postgres
2025-03-05 09:44:25,674 - root - ERROR - Database retail_db already exists
2025-03-05 09:44:25,675 - root - DEBUG - Attempting to connect to retail_db
2025-03-05 09:44:25,707 - root - DEBUG - Connected successfully to retail_db
2025-03-05 09:44:25,708 - root - DEBUG - Executing tables creation query
2025-03-05 09:44:25,709 - root - INFO - Tables created successfully!
2025-03-05 09:44:25,709 - root - DEBUG - Database conncetion closed
2025-03-05 09:44:26,807 - root - INFO - Dataset read
2025-03-05 09:44:27,087 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-05 09:44:27,151 - root - INFO - Identified 1454 corrupted rows.
2025-03-05 09:44:27,253 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-05 09:44:28,112 - root - INFO - Identified 5268 duplicate rows.
2025-03-05 09:44:28,113 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-05 09:44:28,590 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-05 09:44:28,654 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-05 09:44:28,655 - root - DEBUG - Attempting to connect to retail_db
2025-03-05 09:44:28,685 - root - DEBUG - Connected successfully to retail_db
2025-03-05 09:44:47,412 - root - DEBUG - Attempting to connect to retail_db
2025-03-05 09:44:47,437 - root - DEBUG - Connected successfully to postgres
2025-03-05 09:44:47,438 - root - ERROR - Database retail_db already exists
2025-03-05 09:44:47,439 - root - DEBUG - Attempting to connect to retail_db
2025-03-05 09:44:47,460 - root - DEBUG - Connected successfully to retail_db
2025-03-05 09:44:47,460 - root - DEBUG - Executing tables creation query
2025-03-05 09:44:47,463 - root - INFO - Tables created successfully!
2025-03-05 09:44:47,463 - root - DEBUG - Database conncetion closed
2025-03-05 09:44:48,597 - root - INFO - Dataset read
2025-03-05 09:44:48,903 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-05 09:44:48,984 - root - INFO - Identified 1454 corrupted rows.
2025-03-05 09:44:49,102 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-05 09:44:50,165 - root - INFO - Identified 5268 duplicate rows.
2025-03-05 09:44:50,166 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-05 09:44:50,698 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-05 09:44:50,767 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-05 09:44:50,767 - root - DEBUG - Attempting to connect to retail_db
2025-03-05 09:44:50,796 - root - DEBUG - Connected successfully to retail_db
2025-03-05 09:48:01,517 - root - DEBUG - Attempting to connect to retail_db
2025-03-05 09:48:01,590 - root - DEBUG - Connected successfully to postgres
2025-03-05 09:48:01,592 - root - ERROR - Database retail_db already exists
2025-03-05 09:48:01,596 - root - DEBUG - Attempting to connect to retail_db
2025-03-05 09:48:01,638 - root - DEBUG - Connected successfully to retail_db
2025-03-05 09:48:01,640 - root - DEBUG - Executing tables creation query
2025-03-05 09:48:01,643 - root - INFO - Tables created successfully!
2025-03-05 09:48:01,643 - root - DEBUG - Database conncetion closed
2025-03-05 09:48:19,262 - root - INFO - Dataset read
2025-03-05 09:48:19,539 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-05 09:48:19,603 - root - INFO - Identified 1454 corrupted rows.
2025-03-05 09:48:19,711 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-05 09:48:20,491 - root - INFO - Identified 5268 duplicate rows.
2025-03-05 09:48:20,491 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-05 09:48:20,964 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-05 09:48:21,032 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-05 09:48:21,033 - root - DEBUG - Attempting to connect to retail_db
2025-03-05 09:48:21,056 - root - DEBUG - Connected successfully to retail_db
2025-03-05 09:48:33,260 - root - INFO - Dataset read
2025-03-05 09:48:33,567 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-05 09:48:33,628 - root - INFO - Identified 1454 corrupted rows.
2025-03-05 09:48:33,735 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-05 09:48:34,569 - root - INFO - Identified 5268 duplicate rows.
2025-03-05 09:48:34,569 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-05 09:48:35,057 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-05 09:48:35,134 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-05 09:48:35,134 - root - DEBUG - Attempting to connect to retail_db
2025-03-05 09:48:35,159 - root - DEBUG - Connected successfully to retail_db
2025-03-05 10:00:43,330 - root - INFO - Dataset read
2025-03-05 10:00:43,630 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-05 10:00:43,694 - root - INFO - Identified 1454 corrupted rows.
2025-03-05 10:00:43,826 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-05 10:00:44,783 - root - INFO - Identified 5268 duplicate rows.
2025-03-05 10:00:44,784 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-05 10:00:45,388 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-05 10:00:45,463 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-06 07:09:17,857 - root - INFO - Dataset read
2025-03-06 07:09:18,134 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-06 07:09:18,196 - root - INFO - Identified 1454 corrupted rows.
2025-03-06 07:09:18,324 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-06 07:09:19,233 - root - INFO - Identified 5268 duplicate rows.
2025-03-06 07:09:19,233 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-06 07:09:19,736 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-06 07:09:19,825 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-06 07:09:19,825 - root - DEBUG - Attempting to connect to retail_db
2025-03-06 07:09:19,872 - root - DEBUG - Connected successfully to retail_db
2025-03-06 07:17:32,153 - root - INFO - Dataset read
2025-03-06 07:17:32,492 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-06 07:17:32,556 - root - INFO - Identified 1454 corrupted rows.
2025-03-06 07:17:32,679 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-06 07:17:33,775 - root - INFO - Identified 5268 duplicate rows.
2025-03-06 07:17:33,777 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-06 07:17:34,371 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-06 07:17:34,483 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-06 07:53:27,076 - root - INFO - Dataset read
2025-03-06 07:53:27,367 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-06 07:53:27,434 - root - INFO - Identified 1454 corrupted rows.
2025-03-06 07:53:27,542 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-06 07:53:28,424 - root - INFO - Identified 5268 duplicate rows.
2025-03-06 07:53:28,425 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-06 07:53:28,905 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-06 07:53:28,972 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-06 07:53:28,973 - root - DEBUG - Attempting to connect to retail_db
2025-03-06 07:53:28,993 - root - DEBUG - Connected successfully to retail_db
2025-03-06 07:53:59,985 - root - INFO - Dataset read
2025-03-06 07:54:00,269 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-06 07:54:00,337 - root - INFO - Identified 1454 corrupted rows.
2025-03-06 07:54:00,455 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-06 07:54:01,367 - root - INFO - Identified 5268 duplicate rows.
2025-03-06 07:54:01,368 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-06 07:54:01,864 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-06 07:54:01,927 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-06 07:54:01,927 - root - DEBUG - Attempting to connect to retail_db
2025-03-06 07:54:01,952 - root - DEBUG - Connected successfully to retail_db
2025-03-06 07:55:05,977 - root - INFO - Dataset read
2025-03-06 07:55:06,276 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-06 07:55:06,343 - root - INFO - Identified 1454 corrupted rows.
2025-03-06 07:55:06,475 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-06 07:55:07,460 - root - INFO - Identified 5268 duplicate rows.
2025-03-06 07:55:07,461 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-06 07:55:08,017 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-06 07:55:08,092 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-06 08:00:53,702 - root - INFO - Dataset read
2025-03-06 08:00:53,991 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-06 08:00:54,078 - root - INFO - Identified 1454 corrupted rows.
2025-03-06 08:00:54,230 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-06 08:00:55,278 - root - INFO - Identified 5268 duplicate rows.
2025-03-06 08:00:55,278 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-06 08:00:55,774 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-06 08:00:55,854 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-06 08:00:55,987 - root - DEBUG - Attempting to connect to retail_db
2025-03-06 08:00:56,009 - root - DEBUG - Connected successfully to retail_db
2025-03-06 08:01:21,038 - root - INFO - Dataset read
2025-03-06 08:01:21,323 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-06 08:01:21,399 - root - INFO - Identified 1454 corrupted rows.
2025-03-06 08:01:21,503 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-06 08:01:22,304 - root - INFO - Identified 5268 duplicate rows.
2025-03-06 08:01:22,304 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-06 08:01:22,800 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-06 08:01:22,865 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-06 08:01:22,998 - root - DEBUG - Attempting to connect to retail_db
2025-03-06 08:01:23,021 - root - DEBUG - Connected successfully to retail_db
2025-03-06 08:02:19,585 - root - INFO - Dataset read
2025-03-06 08:02:19,858 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-06 08:02:19,919 - root - INFO - Identified 1454 corrupted rows.
2025-03-06 08:02:20,020 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-06 08:02:20,831 - root - INFO - Identified 5268 duplicate rows.
2025-03-06 08:02:20,831 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-06 08:02:21,314 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-06 08:02:21,385 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-06 08:02:21,525 - root - DEBUG - Attempting to connect to retail_db
2025-03-06 08:02:21,549 - root - DEBUG - Connected successfully to retail_db
2025-03-06 08:02:37,787 - root - INFO - Dataset read
2025-03-06 08:02:38,068 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-06 08:02:38,142 - root - INFO - Identified 1454 corrupted rows.
2025-03-06 08:02:38,248 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-06 08:02:39,094 - root - INFO - Identified 5268 duplicate rows.
2025-03-06 08:02:39,095 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-06 08:02:39,646 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-06 08:02:39,732 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-06 08:02:39,745 - root - DEBUG - Attempting to connect to retail_db
2025-03-06 08:02:39,767 - root - DEBUG - Connected successfully to retail_db
2025-03-06 08:05:46,465 - root - INFO - Dataset read
2025-03-06 08:05:46,738 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-06 08:05:46,797 - root - INFO - Identified 1454 corrupted rows.
2025-03-06 08:05:46,899 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-06 08:05:47,673 - root - INFO - Identified 5268 duplicate rows.
2025-03-06 08:05:47,674 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-06 08:05:48,144 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-06 08:05:48,205 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-06 08:05:48,216 - root - DEBUG - Attempting to connect to retail_db
2025-03-06 08:05:48,238 - root - DEBUG - Connected successfully to retail_db
2025-03-11 05:04:14,314 - root - INFO - Dataset read
2025-03-11 05:04:14,637 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-11 05:04:14,713 - root - INFO - Identified 1454 corrupted rows.
2025-03-11 05:04:14,852 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-11 05:04:15,915 - root - INFO - Identified 5268 duplicate rows.
2025-03-11 05:04:15,917 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-11 05:04:16,674 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-11 05:04:16,770 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-11 05:56:21,803 - root - INFO - Dataset read
2025-03-11 05:56:22,079 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-11 05:56:22,139 - root - INFO - Identified 1454 corrupted rows.
2025-03-11 05:56:22,242 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-11 05:56:23,025 - root - INFO - Identified 5268 duplicate rows.
2025-03-11 05:56:23,025 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-11 05:56:23,577 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-11 05:56:23,644 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-11 05:56:23,905 - root - DEBUG - Attempting to connect to retail_db
2025-03-11 05:56:23,925 - root - DEBUG - Connected successfully to retail_db
2025-03-11 05:56:23,938 - root - ERROR - Data insertion error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.

2025-03-11 05:56:40,397 - root - INFO - Dataset read
2025-03-11 05:56:40,673 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-11 05:56:40,738 - root - INFO - Identified 1454 corrupted rows.
2025-03-11 05:56:40,844 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-11 05:56:41,606 - root - INFO - Identified 5268 duplicate rows.
2025-03-11 05:56:41,606 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-11 05:56:42,117 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-11 05:56:42,182 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-11 05:56:42,391 - root - DEBUG - Attempting to connect to retail_db
2025-03-11 05:56:42,412 - root - DEBUG - Connected successfully to retail_db
2025-03-11 05:58:08,093 - root - INFO - Dataset read
2025-03-11 05:58:08,390 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-11 05:58:08,456 - root - INFO - Identified 1454 corrupted rows.
2025-03-11 05:58:08,566 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-11 05:58:09,521 - root - INFO - Identified 5268 duplicate rows.
2025-03-11 05:58:09,522 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-11 05:58:10,090 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-11 05:58:10,164 - root - INFO - Dataset successfully partitioned into Data frames.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     2025-03-11 07:11:11,328 - root - INFO - Dataset read
2025-03-11 07:11:11,606 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-11 07:11:11,668 - root - INFO - Identified 1454 corrupted rows.
2025-03-11 07:11:11,777 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-11 07:11:12,560 - root - INFO - Identified 5268 duplicate rows.
2025-03-11 07:11:12,560 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-11 07:11:13,042 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-11 07:11:13,106 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-11 07:11:13,308 - root - DEBUG - Attempting to connect to retail_db
2025-03-11 07:11:13,355 - root - DEBUG - Connected successfully to retail_db
2025-03-11 07:11:13,355 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-11 07:11:13,398 - root - ERROR - Error inserting data into customer table: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.

2025-03-11 07:11:13,515 - root - ERROR - Error inserting data into invoice table: duplicate key value violates unique constraint "invoice_pkey"
DETAIL:  Key (invoiceno)=(536365) already exists.

2025-03-11 07:12:19,831 - root - INFO - Dataset read
2025-03-11 07:12:20,100 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-11 07:12:20,158 - root - INFO - Identified 1454 corrupted rows.
2025-03-11 07:12:20,256 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-11 07:12:20,983 - root - INFO - Identified 5268 duplicate rows.
2025-03-11 07:12:20,983 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-11 07:12:21,476 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-11 07:12:21,539 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-11 07:12:21,740 - root - DEBUG - Attempting to connect to retail_db
2025-03-11 07:12:21,763 - root - DEBUG - Connected successfully to retail_db
2025-03-11 07:12:21,763 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-11 07:12:21,774 - root - ERROR - Error inserting data into customer table: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.

2025-03-11 07:12:21,926 - root - ERROR - Error inserting data into invoice table: duplicate key value violates unique constraint "invoice_pkey"
DETAIL:  Key (invoiceno)=(536365) already exists.

2025-03-11 07:12:22,857 - root - ERROR - Errors inserting data into invoice_details table: insert or update on table "invoice_details" violates foreign key constraint "invoice_details_stockcode_fkey"
DETAIL:  Key (stockcode)=(85123A) is not present in table "product".

2025-03-11 07:12:27,695 - root - INFO - Data inserted correctly into product table
2025-03-11 07:15:59,945 - root - INFO - Dataset read
2025-03-11 07:16:00,230 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-11 07:16:00,288 - root - INFO - Identified 1454 corrupted rows.
2025-03-11 07:16:00,384 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-11 07:16:01,183 - root - INFO - Identified 5268 duplicate rows.
2025-03-11 07:16:01,183 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-11 07:16:01,754 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-11 07:16:01,821 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-11 07:16:02,038 - root - DEBUG - Attempting to connect to retail_db
2025-03-11 07:16:02,058 - root - DEBUG - Connected successfully to retail_db
2025-03-11 07:16:02,058 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-11 07:16:02,070 - root - ERROR - Error inserting data into customer table: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.

2025-03-11 07:16:02,159 - root - ERROR - Error inserting data into invoice table: duplicate key value violates unique constraint "invoice_pkey"
DETAIL:  Key (invoiceno)=(536365) already exists.

2025-03-11 07:16:02,168 - root - ERROR - Error inserting data into product table: duplicate key value violates unique constraint "product_pkey"
DETAIL:  Key (stockcode)=(85123A) already exists.

2025-03-11 07:17:19,533 - root - ERROR - Errors inserting data into invoice_details table: smallint out of range

2025-03-11 07:18:25,003 - root - INFO - Dataset read
2025-03-11 07:18:25,307 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-11 07:18:25,374 - root - INFO - Identified 1454 corrupted rows.
2025-03-11 07:18:25,480 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-11 07:18:26,569 - root - INFO - Identified 5268 duplicate rows.
2025-03-11 07:18:26,570 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-11 07:18:27,142 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-11 07:18:27,215 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-11 07:18:27,470 - root - DEBUG - Attempting to connect to retail_db
2025-03-11 07:18:27,501 - root - DEBUG - Connected successfully to retail_db
2025-03-11 07:18:27,503 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-11 07:18:27,517 - root - ERROR - Error inserting data into customer table: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.

2025-03-11 07:18:27,641 - root - ERROR - Error inserting data into invoice table: duplicate key value violates unique constraint "invoice_pkey"
DETAIL:  Key (invoiceno)=(536365) already exists.

2025-03-11 07:18:27,655 - root - ERROR - Error inserting data into product table: duplicate key value violates unique constraint "product_pkey"
DETAIL:  Key (stockcode)=(85123A) already exists.

2025-03-11 07:18:28,613 - root - ERROR - Errors inserting data into invoice_details table: duplicate key value violates unique constraint "invoice_details_pkey"
DETAIL:  Key (invoiceno, stockcode)=(536365, 85123A) already exists.

2025-03-11 07:49:25,439 - root - INFO - Dataset read
2025-03-11 07:49:25,729 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-11 07:49:25,804 - root - INFO - Identified 1454 corrupted rows.
2025-03-11 07:49:25,902 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-11 07:49:26,675 - root - INFO - Identified 5268 duplicate rows.
2025-03-11 07:49:26,676 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-11 07:49:27,185 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-11 07:49:27,252 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-11 07:49:27,462 - root - DEBUG - Attempting to connect to retail_db
2025-03-11 07:49:27,484 - root - ERROR - Connection error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  database "retail_db" does not exist

2025-03-11 07:49:36,796 - root - DEBUG - Attempting to connect to retail_db
2025-03-11 07:49:36,821 - root - DEBUG - Connected successfully to postgres
2025-03-11 07:49:37,052 - root - INFO - Database retail_db created!
2025-03-11 07:49:37,052 - root - DEBUG - Attempting to connect to retail_db
2025-03-11 07:49:37,077 - root - DEBUG - Connected successfully to retail_db
2025-03-11 07:49:37,078 - root - DEBUG - Executing tables creation query
2025-03-11 07:49:37,106 - root - INFO - Tables created successfully!
2025-03-11 07:49:37,107 - root - DEBUG - Database conncetion closed
2025-03-11 07:50:15,983 - root - INFO - Dataset read
2025-03-11 07:50:16,270 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-11 07:50:16,329 - root - INFO - Identified 1454 corrupted rows.
2025-03-11 07:50:16,434 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-11 07:50:17,273 - root - INFO - Identified 5268 duplicate rows.
2025-03-11 07:50:17,273 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-11 07:50:17,763 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-11 07:50:17,825 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-11 07:50:18,033 - root - DEBUG - Attempting to connect to retail_db
2025-03-11 07:50:18,057 - root - DEBUG - Connected successfully to retail_db
2025-03-11 07:50:18,058 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-11 07:50:23,215 - root - INFO - Data inserted correctly into customer table
2025-03-11 07:50:52,953 - root - INFO - Data inserted correctly into invoice table
2025-03-11 07:50:57,811 - root - INFO - Data inserted correctly into product table
2025-03-11 10:10:26,694 - root - INFO - Dataset read
2025-03-11 10:10:26,986 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-11 10:10:27,052 - root - INFO - Identified 1454 corrupted rows.
2025-03-11 10:10:27,151 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-11 10:10:27,876 - root - INFO - Identified 5268 duplicate rows.
2025-03-11 10:10:27,876 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-11 10:10:28,344 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-11 10:10:28,403 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-11 10:10:28,603 - root - DEBUG - Attempting to connect to retail_db
2025-03-11 10:10:28,624 - root - DEBUG - Connected successfully to retail_db
2025-03-11 10:10:28,624 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-11 10:10:28,635 - root - ERROR - Error inserting data into customer table: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.

2025-03-11 10:10:28,712 - root - ERROR - Error inserting data into invoice table: duplicate key value violates unique constraint "invoice_pkey"
DETAIL:  Key (invoiceno)=(536365) already exists.

2025-03-11 10:10:28,721 - root - ERROR - Error inserting data into product table: duplicate key value violates unique constraint "product_pkey"
DETAIL:  Key (stockcode)=(85123A) already exists.

2025-03-11 10:10:29,559 - root - ERROR - Errors inserting data into invoice_details table: duplicate key value violates unique constraint "invoice_details_pkey"
DETAIL:  Key (invoiceno, stockcode)=(536365, 85123A) already exists.

2025-03-11 10:12:40,126 - root - INFO - Dataset read
2025-03-11 10:12:40,433 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-11 10:12:40,495 - root - INFO - Identified 1454 corrupted rows.
2025-03-11 10:12:40,607 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-11 10:12:41,497 - root - INFO - Identified 5268 duplicate rows.
2025-03-11 10:12:41,499 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-11 10:12:42,050 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-11 10:12:42,119 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-11 10:12:42,368 - root - DEBUG - Attempting to connect to retail_db
2025-03-11 10:12:42,390 - root - DEBUG - Connected successfully to retail_db
2025-03-11 10:12:42,393 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-11 10:12:42,407 - root - ERROR - Error inserting data into customer table: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.

2025-03-11 10:12:42,515 - root - ERROR - Error inserting data into invoice table: duplicate key value violates unique constraint "invoice_pkey"
DETAIL:  Key (invoiceno)=(536365) already exists.

2025-03-11 10:12:42,530 - root - ERROR - Error inserting data into product table: duplicate key value violates unique constraint "product_pkey"
DETAIL:  Key (stockcode)=(85123A) already exists.

2025-03-11 10:12:43,433 - root - ERROR - Errors inserting data into invoice_details table: duplicate key value violates unique constraint "invoice_details_pkey"
DETAIL:  Key (invoiceno, stockcode)=(536365, 85123A) already exists.

2025-03-12 04:11:17,765 - root - DEBUG - Attempting to connect to retail_db
2025-03-12 04:11:17,793 - root - DEBUG - Connected successfully to postgres
2025-03-12 04:11:17,834 - root - INFO - Database retail_db created!
2025-03-12 04:11:17,836 - root - DEBUG - Attempting to connect to retail_db
2025-03-12 04:11:17,871 - root - DEBUG - Connected successfully to retail_db
2025-03-12 04:11:17,871 - root - DEBUG - Executing tables creation query
2025-03-12 04:11:17,896 - root - INFO - Tables created successfully!
2025-03-12 04:11:17,896 - root - DEBUG - Database conncetion closed
2025-03-12 04:11:29,839 - root - INFO - Dataset read
2025-03-12 04:11:30,111 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-12 04:11:30,170 - root - INFO - Identified 1454 corrupted rows.
2025-03-12 04:11:30,274 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-12 04:11:31,024 - root - INFO - Identified 5268 duplicate rows.
2025-03-12 04:11:31,025 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-12 04:11:31,523 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-12 04:11:31,593 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-12 04:11:31,802 - root - DEBUG - Attempting to connect to retail_db
2025-03-12 04:11:31,822 - root - DEBUG - Connected successfully to retail_db
2025-03-12 04:11:31,822 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-12 04:11:37,351 - root - INFO - Data inserted correctly into customer table
2025-03-12 04:12:07,135 - root - INFO - Data inserted correctly into invoice table
2025-03-12 04:12:12,102 - root - INFO - Data inserted correctly into product table
2025-03-12 04:23:44,236 - root - INFO - Data inserted correctly into invoice_details table
2025-03-12 04:31:25,550 - root - DEBUG - Attempting to connect to retail_db
2025-03-12 04:31:25,576 - root - DEBUG - Connected successfully to postgres
2025-03-12 04:31:25,617 - root - INFO - Database retail_db created!
2025-03-12 04:31:25,621 - root - DEBUG - Attempting to connect to retail_db
2025-03-12 04:31:25,658 - root - DEBUG - Connected successfully to retail_db
2025-03-12 04:31:25,659 - root - DEBUG - Executing tables creation query
2025-03-12 04:31:25,681 - root - INFO - Tables created successfully!
2025-03-12 04:31:25,682 - root - DEBUG - Database conncetion closed
2025-03-12 04:31:31,813 - root - INFO - Dataset read
2025-03-12 04:31:32,111 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-12 04:31:32,178 - root - INFO - Identified 1454 corrupted rows.
2025-03-12 04:31:32,308 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-12 04:31:33,177 - root - INFO - Identified 5268 duplicate rows.
2025-03-12 04:31:33,178 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-12 04:31:33,657 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-12 04:31:33,735 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-12 04:31:33,944 - root - DEBUG - Attempting to connect to retail_db
2025-03-12 04:31:33,965 - root - DEBUG - Connected successfully to retail_db
2025-03-12 04:31:33,965 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-12 04:31:39,156 - root - INFO - Data inserted correctly into customer table
2025-03-12 04:32:09,990 - root - INFO - Data inserted correctly into invoice table
2025-03-12 04:32:15,083 - root - INFO - Data inserted correctly into product table
2025-03-12 04:43:14,615 - root - INFO - Data inserted correctly into invoice_details table
2025-03-12 04:43:14,616 - root - INFO - operateion took 658.61 seconds
2025-03-12 04:48:59,732 - root - INFO - Dataset read
2025-03-12 04:49:00,028 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-12 04:49:00,090 - root - INFO - Identified 1454 corrupted rows.
2025-03-12 04:49:00,195 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-12 04:49:01,087 - root - INFO - Identified 5268 duplicate rows.
2025-03-12 04:49:01,087 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-12 04:49:01,616 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-12 04:49:01,691 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-12 04:49:01,932 - root - DEBUG - Attempting to connect to retail_db
2025-03-12 04:49:01,960 - root - DEBUG - Connected successfully to retail_db
2025-03-12 04:49:01,960 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-12 04:49:01,973 - root - ERROR - Error inserting data into customer table: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.

2025-03-12 04:49:02,069 - root - ERROR - Error inserting data into invoice table: duplicate key value violates unique constraint "invoice_pkey"
DETAIL:  Key (invoiceno)=(536365) already exists.

2025-03-12 04:49:02,079 - root - ERROR - Error inserting data into product table: duplicate key value violates unique constraint "product_pkey"
DETAIL:  Key (stockcode)=(85123A) already exists.

2025-03-12 04:59:01,948 - root - INFO - Data inserted correctly into invoice_details table
2025-03-12 04:59:01,948 - root - INFO - operateion took 598.91 seconds
2025-03-12 05:47:40,764 - root - INFO - Dataset read
2025-03-12 05:47:41,039 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-12 05:47:41,098 - root - INFO - Identified 1454 corrupted rows.
2025-03-12 05:47:41,198 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-12 05:47:41,947 - root - INFO - Identified 5268 duplicate rows.
2025-03-12 05:47:41,948 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-12 05:47:42,431 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-12 05:47:42,494 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-12 05:47:42,709 - root - DEBUG - Attempting to connect to retail_db
2025-03-12 05:47:42,729 - root - DEBUG - Connected successfully to retail_db
2025-03-12 05:47:42,729 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-12 05:47:42,742 - root - ERROR - Error inserting data into customer table: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.

2025-03-12 05:47:42,831 - root - ERROR - Error inserting data into invoice table: duplicate key value violates unique constraint "invoice_pkey"
DETAIL:  Key (invoiceno)=(536365) already exists.

2025-03-12 05:47:42,843 - root - ERROR - Error inserting data into product table: duplicate key value violates unique constraint "product_pkey"
DETAIL:  Key (stockcode)=(85123A) already exists.

2025-03-12 05:58:51,352 - root - INFO - Data inserted correctly into invoice_details table
2025-03-12 05:58:51,352 - root - INFO - operateion took 667.58 seconds
2025-03-12 06:16:55,345 - root - INFO - Dataset read
2025-03-12 06:16:55,613 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-12 06:16:55,671 - root - INFO - Identified 1454 corrupted rows.
2025-03-12 06:16:55,768 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-12 06:16:56,531 - root - INFO - Identified 5268 duplicate rows.
2025-03-12 06:16:56,531 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-12 06:16:57,008 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-12 06:16:57,072 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-12 06:16:57,279 - root - DEBUG - Attempting to connect to retail_db
2025-03-12 06:16:57,306 - root - DEBUG - Connected successfully to retail_db
2025-03-12 06:16:57,306 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-12 06:16:57,317 - root - ERROR - Error inserting data into customer table: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.

2025-03-12 06:16:57,397 - root - ERROR - Error inserting data into invoice table: duplicate key value violates unique constraint "invoice_pkey"
DETAIL:  Key (invoiceno)=(536365) already exists.

2025-03-12 06:16:57,408 - root - ERROR - Error inserting data into product table: duplicate key value violates unique constraint "product_pkey"
DETAIL:  Key (stockcode)=(85123A) already exists.

2025-03-12 06:17:12,745 - root - INFO - Data inserted correctly into invoice_details table
2025-03-12 06:17:12,745 - root - INFO - operateion took 15.34 seconds
2025-03-12 08:15:16,957 - root - INFO - Dataset read
2025-03-12 08:15:17,250 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-12 08:15:17,325 - root - INFO - Identified 1454 corrupted rows.
2025-03-12 08:15:17,450 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-12 08:15:18,388 - root - INFO - Identified 5268 duplicate rows.
2025-03-12 08:15:18,390 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-12 08:15:18,962 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-12 08:15:19,031 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-12 08:15:19,296 - root - DEBUG - Attempting to connect to retail_db
2025-03-12 08:15:19,337 - root - DEBUG - Connected successfully to retail_db
2025-03-12 08:15:19,339 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-12 08:15:19,356 - root - ERROR - Error inserting data into customer table: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.

2025-03-12 08:15:19,464 - root - ERROR - Error inserting data into invoice table: duplicate key value violates unique constraint "invoice_pkey"
DETAIL:  Key (invoiceno)=(536365) already exists.

2025-03-12 08:15:19,478 - root - ERROR - Error inserting data into product table: duplicate key value violates unique constraint "product_pkey"
DETAIL:  Key (stockcode)=(85123A) already exists.

2025-03-12 08:15:20,250 - root - INFO - Data inserted correctly into invoice_details table
2025-03-12 08:21:38,591 - root - INFO - Dataset read
2025-03-12 08:21:38,857 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-12 08:21:38,917 - root - INFO - Identified 1454 corrupted rows.
2025-03-12 08:21:39,019 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-12 08:21:39,831 - root - INFO - Identified 5268 duplicate rows.
2025-03-12 08:21:39,831 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-12 08:21:40,320 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-12 08:21:40,389 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-12 08:21:40,607 - root - DEBUG - Attempting to connect to retail_db
2025-03-12 08:21:40,627 - root - DEBUG - Connected successfully to retail_db
2025-03-12 08:21:40,627 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-12 08:21:40,639 - root - ERROR - Error inserting data into customer table: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.

2025-03-12 08:21:40,718 - root - ERROR - Error inserting data into invoice table: duplicate key value violates unique constraint "invoice_pkey"
DETAIL:  Key (invoiceno)=(536365) already exists.

2025-03-12 08:21:40,727 - root - ERROR - Error inserting data into product table: duplicate key value violates unique constraint "product_pkey"
DETAIL:  Key (stockcode)=(85123A) already exists.

2025-03-12 08:21:41,448 - root - ERROR - Errors inserting data into invoice_details table: relation "invoice_table" does not exist

2025-03-12 08:22:01,877 - root - INFO - Dataset read
2025-03-12 08:22:02,153 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-12 08:22:02,215 - root - INFO - Identified 1454 corrupted rows.
2025-03-12 08:22:02,321 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-12 08:22:03,103 - root - INFO - Identified 5268 duplicate rows.
2025-03-12 08:22:03,103 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-12 08:22:03,621 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-12 08:22:03,684 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-12 08:22:03,895 - root - DEBUG - Attempting to connect to retail_db
2025-03-12 08:22:03,916 - root - DEBUG - Connected successfully to retail_db
2025-03-12 08:22:03,916 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-12 08:22:03,927 - root - ERROR - Error inserting data into customer table: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.

2025-03-12 08:22:04,009 - root - ERROR - Error inserting data into invoice table: duplicate key value violates unique constraint "invoice_pkey"
DETAIL:  Key (invoiceno)=(536365) already exists.

2025-03-12 08:22:04,019 - root - ERROR - Error inserting data into product table: duplicate key value violates unique constraint "product_pkey"
DETAIL:  Key (stockcode)=(85123A) already exists.

2025-03-12 08:22:04,775 - root - ERROR - Errors inserting data into invoice_details table: duplicate key value violates unique constraint "invoice_details_pkey"
DETAIL:  Key (invoiceno, stockcode)=(536365, 85123A) already exists.
CONTEXT:  COPY invoice_details, line 1

2025-03-13 03:38:19,985 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 03:38:20,017 - root - DEBUG - Connected successfully to postgres
2025-03-13 03:38:20,215 - root - INFO - Database retail_db created!
2025-03-13 03:38:20,215 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 03:38:20,237 - root - DEBUG - Connected successfully to retail_db
2025-03-13 03:38:20,238 - root - DEBUG - Database conncetion closed
2025-03-13 03:39:19,728 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 03:39:19,752 - root - DEBUG - Connected successfully to postgres
2025-03-13 03:39:19,754 - root - ERROR - Database retail_db already exists
2025-03-13 03:39:19,754 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 03:39:19,783 - root - DEBUG - Connected successfully to retail_db
2025-03-13 03:39:19,783 - root - DEBUG - Executing tables creation query
2025-03-13 03:39:19,806 - root - INFO - Tables created successfully!
2025-03-13 03:39:19,807 - root - DEBUG - Database conncetion closed
2025-03-13 03:40:51,548 - root - INFO - Dataset read
2025-03-13 03:40:51,828 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 03:40:51,889 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 03:40:51,997 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 03:40:52,751 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 03:40:52,751 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 03:40:53,224 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 03:40:53,283 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 03:40:53,495 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 03:40:53,518 - root - DEBUG - Connected successfully to retail_db
2025-03-13 03:40:53,518 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 03:41:07,722 - root - INFO - Dataset read
2025-03-13 03:41:07,991 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 03:41:08,051 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 03:41:08,147 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 03:41:08,879 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 03:41:08,879 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 03:41:09,345 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 03:41:09,418 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 03:41:09,628 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 03:41:09,648 - root - DEBUG - Connected successfully to retail_db
2025-03-13 03:41:09,648 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 03:41:09,659 - root - ERROR - Unexpected Error: relation "customer" does not exist
LINE 1: INSERT INTO customer (customerid, country) VALUES(17850, 'Un...
                    ^

2025-03-13 03:43:24,656 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 03:43:24,693 - root - DEBUG - Connected successfully to postgres
2025-03-13 03:43:24,695 - root - ERROR - Database retail_db already exists
2025-03-13 03:43:24,695 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 03:43:24,733 - root - DEBUG - Connected successfully to retail_db
2025-03-13 03:43:24,733 - root - DEBUG - Executing tables creation query
2025-03-13 03:43:24,757 - root - INFO - Tables created successfully!
2025-03-13 03:43:24,760 - root - DEBUG - Database conncetion closed
2025-03-13 03:43:34,910 - root - INFO - Dataset read
2025-03-13 03:43:35,261 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 03:43:35,324 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 03:43:35,424 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 03:43:36,208 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 03:43:36,208 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 03:43:36,692 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 03:43:36,754 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 03:43:36,955 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 03:43:36,975 - root - DEBUG - Connected successfully to retail_db
2025-03-13 03:43:36,975 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 03:43:37,359 - root - INFO - Data inserted correctly into customer table
2025-03-13 03:43:41,242 - root - INFO - Data inserted correctly into invoice table
2025-03-13 03:43:41,702 - root - INFO - Data inserted correctly into product table
2025-03-13 03:43:58,054 - root - INFO - Data inserted correctly into invoice_details table
2025-03-13 03:43:58,057 - root - INFO - All data committed successfully
2025-03-13 03:45:32,652 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 03:45:32,676 - root - DEBUG - Connected successfully to postgres
2025-03-13 03:45:32,677 - root - ERROR - Database retail_db already exists
2025-03-13 03:45:32,677 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 03:45:32,715 - root - DEBUG - Connected successfully to retail_db
2025-03-13 03:45:32,716 - root - DEBUG - Executing tables creation query
2025-03-13 03:45:32,717 - root - INFO - Tables created successfully!
2025-03-13 03:45:32,717 - root - DEBUG - Database conncetion closed
2025-03-13 03:47:07,764 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 03:47:07,798 - root - DEBUG - Connected successfully to postgres
2025-03-13 03:47:07,801 - root - ERROR - Database retail_db already exists
2025-03-13 03:49:47,404 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 03:49:47,436 - root - DEBUG - Connected successfully to postgres
2025-03-13 03:50:46,695 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 03:50:46,723 - root - DEBUG - Connected successfully to postgres
2025-03-13 03:51:56,016 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 03:51:56,044 - root - DEBUG - Connected successfully to postgres
2025-03-13 04:13:22,362 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 04:13:22,386 - root - DEBUG - Connected successfully to postgres
2025-03-13 04:13:22,435 - root - INFO - Database retail_db created!
2025-03-13 04:13:22,438 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 04:13:22,490 - root - DEBUG - Connected successfully to retail_db
2025-03-13 04:13:22,491 - root - DEBUG - Executing tables creation query
2025-03-13 04:13:22,517 - root - INFO - Tables created successfully!
2025-03-13 04:13:22,517 - root - DEBUG - Database conncetion closed
2025-03-13 04:13:48,867 - root - INFO - Dataset read
2025-03-13 04:13:49,141 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 04:13:49,199 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 04:13:49,296 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 04:13:50,169 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 04:13:50,169 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 04:13:50,660 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 04:13:50,750 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 04:13:50,956 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 04:13:50,982 - root - DEBUG - Connected successfully to retail_db
2025-03-13 04:13:50,982 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 04:13:51,523 - root - INFO - Data inserted correctly into customer table
2025-03-13 04:13:55,361 - root - INFO - Data inserted correctly into invoice table
2025-03-13 04:13:55,878 - root - INFO - Data inserted correctly into product table
2025-03-13 04:14:12,815 - root - INFO - Data inserted correctly into invoice_details table
2025-03-13 04:14:12,817 - root - INFO - All data committed successfully
2025-03-13 04:14:20,202 - root - INFO - Dataset read
2025-03-13 04:14:20,487 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 04:14:20,572 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 04:14:20,678 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 04:14:21,478 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 04:14:21,479 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 04:14:21,980 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 04:14:22,045 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 04:14:22,257 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 04:14:22,277 - root - DEBUG - Connected successfully to retail_db
2025-03-13 04:14:22,277 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 04:14:22,288 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.

2025-03-13 05:14:43,395 - root - INFO - Dataset read
2025-03-13 05:14:43,660 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 05:14:43,721 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 05:14:43,825 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 05:14:44,652 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 05:14:44,652 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 05:14:45,129 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 05:14:45,207 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 05:14:45,424 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 05:14:45,447 - root - DEBUG - Connected successfully to retail_db
2025-03-13 05:14:45,447 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 05:14:45,465 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-13 05:16:15,188 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 05:16:15,215 - root - DEBUG - Connected successfully to postgres
2025-03-13 05:16:15,262 - root - INFO - Database retail_db created!
2025-03-13 05:16:15,262 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 05:16:15,290 - root - DEBUG - Connected successfully to retail_db
2025-03-13 05:16:15,291 - root - DEBUG - Executing tables creation query
2025-03-13 05:16:15,314 - root - INFO - Tables created successfully!
2025-03-13 05:16:15,314 - root - DEBUG - Database conncetion closed
2025-03-13 05:16:21,671 - root - INFO - Dataset read
2025-03-13 05:16:21,940 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 05:16:21,997 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 05:16:22,104 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 05:16:22,861 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 05:16:22,862 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 05:16:23,342 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 05:16:23,408 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 05:16:23,618 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 05:16:23,638 - root - DEBUG - Connected successfully to retail_db
2025-03-13 05:16:23,638 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 05:18:36,496 - root - INFO - Dataset read
2025-03-13 05:18:36,762 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 05:18:36,821 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 05:18:36,915 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 05:18:37,709 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 05:18:37,709 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 05:18:38,201 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 05:18:38,283 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 05:18:38,501 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 05:18:38,524 - root - DEBUG - Connected successfully to retail_db
2025-03-13 05:18:38,524 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 05:18:38,544 - root - INFO - Data inserted into customer
2025-03-13 05:23:59,807 - root - INFO - Dataset read
2025-03-13 05:24:00,082 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 05:24:00,144 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 05:24:00,247 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 05:24:01,116 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 05:24:01,117 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 05:24:01,604 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 05:24:01,683 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 05:24:01,903 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 05:24:01,925 - root - DEBUG - Connected successfully to retail_db
2025-03-13 05:24:01,925 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 05:24:01,936 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-13 05:25:52,773 - root - INFO - Dataset read
2025-03-13 05:25:53,046 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 05:25:53,106 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 05:25:53,206 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 05:25:53,980 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 05:25:53,980 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 05:25:54,465 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 05:25:54,527 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 05:25:54,736 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 05:25:54,757 - root - DEBUG - Connected successfully to retail_db
2025-03-13 05:25:54,757 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 05:25:54,787 - root - INFO - Data inserted into customer
2025-03-13 05:25:55,209 - root - INFO - Data inserted into invoice
2025-03-13 05:27:04,169 - root - INFO - Dataset read
2025-03-13 05:27:04,442 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 05:27:04,503 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 05:27:04,605 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 05:27:05,387 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 05:27:05,388 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 05:27:05,864 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 05:27:05,924 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 05:27:06,136 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 05:27:06,157 - root - DEBUG - Connected successfully to retail_db
2025-03-13 05:27:06,158 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 05:27:06,185 - root - INFO - Data inserted into customer
2025-03-13 05:27:06,606 - root - INFO - Data inserted into invoice
2025-03-13 05:27:06,619 - root - ERROR - Unexpected Error: extra data after last expected column
CONTEXT:  COPY product, line 83: "82567,2.1,"AIRLINE LOUNGE,METAL SIGN""

2025-03-13 05:31:08,328 - root - INFO - Dataset read
2025-03-13 05:31:08,598 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 05:31:08,658 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 05:31:08,761 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 05:31:09,502 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 05:31:09,502 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 05:31:09,968 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 05:31:10,028 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 05:31:10,234 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 05:31:10,259 - root - DEBUG - Connected successfully to retail_db
2025-03-13 05:31:10,259 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 05:31:10,279 - root - INFO - Data inserted into customer
2025-03-13 05:31:10,697 - root - INFO - Data inserted into invoice
2025-03-13 05:31:10,710 - root - ERROR - Unexpected Error: extra data after last expected column
CONTEXT:  COPY product, line 83: "82567,2.1,"AIRLINE LOUNGE,METAL SIGN""

2025-03-13 05:35:15,271 - root - INFO - Dataset read
2025-03-13 05:35:15,533 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 05:35:15,590 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 05:35:15,690 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 05:35:16,432 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 05:35:16,432 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 05:35:16,899 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 05:35:16,958 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 05:35:17,164 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 05:35:17,190 - root - DEBUG - Connected successfully to retail_db
2025-03-13 05:35:17,190 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 05:35:17,212 - root - INFO - Data inserted into customer
2025-03-13 05:35:17,635 - root - INFO - Data inserted into invoice
2025-03-13 05:35:17,666 - root - INFO - Data inserted into product
2025-03-13 05:35:32,298 - root - INFO - Data inserted into invoice_details
2025-03-13 05:35:32,302 - root - INFO - All data committed successfully
2025-03-13 05:53:50,735 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 05:53:50,762 - root - DEBUG - Connected successfully to postgres
2025-03-13 05:53:50,763 - root - ERROR - Database retail_db already exists
2025-03-13 05:53:50,766 - root - INFO - Skipped table creation as database was not created
2025-03-13 05:55:55,200 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 05:55:55,248 - root - DEBUG - Connected successfully to postgres
2025-03-13 05:55:55,251 - root - ERROR - Database retail_db already exists
2025-03-13 05:55:55,251 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 05:55:55,283 - root - DEBUG - Connected successfully to retail_db
2025-03-13 05:55:55,284 - root - DEBUG - Executing tables creation query
2025-03-13 05:55:55,317 - root - INFO - Tables created successfully!
2025-03-13 05:55:55,322 - root - DEBUG - Database conncetion closed
2025-03-13 05:58:08,719 - root - INFO - Dataset read
2025-03-13 05:58:08,990 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 05:58:09,050 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 05:58:09,148 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 05:58:09,926 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 05:58:09,926 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 05:58:10,452 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 05:58:10,519 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 05:58:10,773 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 05:58:10,798 - root - DEBUG - Connected successfully to retail_db
2025-03-13 05:58:10,798 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 05:58:10,828 - root - INFO - None insert into customer out of 4372
2025-03-13 05:58:10,828 - root - INFO - Data inserted into customer
2025-03-13 05:58:11,275 - root - INFO - None insert into invoice out of 24446
2025-03-13 05:58:11,275 - root - INFO - Data inserted into invoice
2025-03-13 05:58:11,312 - root - INFO - None insert into product out of 3958
2025-03-13 05:58:11,312 - root - INFO - Data inserted into product
2025-03-13 05:58:26,797 - root - INFO - None insert into invoice_details out of 529771
2025-03-13 05:58:26,798 - root - INFO - Data inserted into invoice_details
2025-03-13 05:58:26,801 - root - INFO - All data committed successfully
2025-03-13 06:00:42,741 - root - INFO - Dataset read
2025-03-13 06:00:43,012 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 06:00:43,069 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 06:00:43,165 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 06:00:43,902 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 06:00:43,902 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 06:00:44,376 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 06:00:44,438 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 06:00:44,669 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 06:00:44,690 - root - DEBUG - Connected successfully to retail_db
2025-03-13 06:00:44,690 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 06:00:44,713 - root - INFO - 4372 insert into customer out of 4372
2025-03-13 06:00:44,714 - root - INFO - Data inserted into customer
2025-03-13 06:00:45,161 - root - INFO - 24446 insert into invoice out of 24446
2025-03-13 06:00:45,162 - root - INFO - Data inserted into invoice
2025-03-13 06:00:45,192 - root - INFO - 3958 insert into product out of 3958
2025-03-13 06:00:45,192 - root - INFO - Data inserted into product
2025-03-13 06:00:59,941 - root - INFO - 529771 insert into invoice_details out of 529771
2025-03-13 06:00:59,941 - root - INFO - Data inserted into invoice_details
2025-03-13 06:00:59,946 - root - INFO - All data committed successfully
2025-03-13 06:02:37,532 - root - INFO - Dataset read
2025-03-13 06:02:37,795 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 06:02:37,853 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 06:02:37,948 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 06:02:38,726 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 06:02:38,726 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 06:02:39,194 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 06:02:39,257 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 06:02:39,463 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 06:02:39,482 - root - DEBUG - Connected successfully to retail_db
2025-03-13 06:02:39,482 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 06:02:39,504 - root - INFO - Inserted (4372,) into customer
2025-03-13 06:02:39,975 - root - INFO - Inserted (24446,) into invoice
2025-03-13 06:02:40,005 - root - INFO - Inserted (3958,) into product
2025-03-13 06:02:54,831 - root - INFO - Inserted (529771,) into invoice_details
2025-03-13 06:02:54,837 - root - INFO - All data committed successfully
2025-03-13 06:04:25,591 - root - INFO - Dataset read
2025-03-13 06:04:25,856 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 06:04:25,915 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 06:04:26,012 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 06:04:26,788 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 06:04:26,789 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 06:04:27,264 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 06:04:27,325 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 06:04:27,531 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 06:04:27,555 - root - DEBUG - Connected successfully to retail_db
2025-03-13 06:04:27,556 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 06:04:27,569 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-13 06:04:35,508 - root - INFO - Dataset read
2025-03-13 06:04:35,797 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 06:04:35,856 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 06:04:35,958 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 06:04:36,752 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 06:04:36,753 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 06:04:37,238 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 06:04:37,300 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 06:04:37,526 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 06:04:37,550 - root - DEBUG - Connected successfully to retail_db
2025-03-13 06:04:37,550 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 06:04:37,578 - root - INFO - Inserted None into customer
2025-03-13 06:04:38,029 - root - INFO - Inserted None into invoice
2025-03-13 06:04:38,065 - root - INFO - Inserted None into product
2025-03-13 06:04:53,647 - root - INFO - Inserted None into invoice_details
2025-03-13 06:04:53,653 - root - INFO - All data committed successfully
2025-03-13 06:11:21,478 - root - INFO - Dataset read
2025-03-13 06:11:21,800 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 06:11:21,865 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 06:11:21,981 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 06:11:23,122 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 06:11:23,123 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 06:11:23,737 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 06:11:23,849 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 06:25:43,337 - root - INFO - Dataset read
2025-03-13 06:25:43,633 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 06:25:43,692 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 06:25:43,789 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 06:25:44,557 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 06:25:44,557 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 06:25:45,030 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 06:25:45,091 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 06:25:45,304 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 06:25:45,324 - root - DEBUG - Connected successfully to retail_db
2025-03-13 06:25:45,325 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 06:25:45,351 - root - INFO - Inserted 4372 rows into customer
2025-03-13 06:25:45,827 - root - INFO - Inserted 24446 rows into invoice
2025-03-13 06:25:45,857 - root - INFO - Inserted 3958 rows into product
2025-03-13 06:26:00,662 - root - INFO - Inserted 529771 rows into invoice_details
2025-03-13 06:26:00,666 - root - INFO - All data committed successfully
2025-03-13 10:14:25,396 - root - INFO - Dataset read
2025-03-13 10:14:25,670 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 10:14:25,729 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 10:14:25,830 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 10:14:26,584 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 10:14:26,584 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 10:14:27,097 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 10:14:27,164 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 10:14:27,392 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 10:14:27,411 - root - DEBUG - Connected successfully to retail_db
2025-03-13 10:14:27,411 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 10:14:27,424 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-13 10:14:37,704 - root - INFO - Dataset read
2025-03-13 10:14:37,975 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 10:14:38,043 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 10:14:38,143 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 10:14:38,904 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 10:14:38,905 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 10:14:39,401 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 10:14:39,469 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 10:14:39,677 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 10:14:39,699 - root - DEBUG - Connected successfully to retail_db
2025-03-13 10:14:39,699 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 10:14:39,727 - root - INFO - Inserted 4372 rows into customer
2025-03-13 10:14:40,162 - root - INFO - Inserted 24446 rows into invoice
2025-03-13 10:14:40,911 - root - ERROR - Unexpected Error: invalid input syntax for type numeric: "85123A"
CONTEXT:  COPY product, line 1, column unitprice: "85123A"

2025-03-13 10:19:16,455 - root - INFO - Dataset read
2025-03-13 10:19:25,298 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 10:19:25,372 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 10:19:25,489 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 10:19:26,531 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 10:19:26,533 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 10:19:27,333 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 10:19:47,803 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 10:22:07,961 - root - INFO - Dataset read
2025-03-13 10:22:08,231 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-13 10:22:08,297 - root - INFO - Identified 1454 corrupted rows.
2025-03-13 10:22:08,406 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-13 10:22:09,250 - root - INFO - Identified 5268 duplicate rows.
2025-03-13 10:22:09,256 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-13 10:22:09,735 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-13 10:22:09,831 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-13 10:22:10,040 - root - DEBUG - Attempting to connect to retail_db
2025-03-13 10:22:10,059 - root - DEBUG - Connected successfully to retail_db
2025-03-13 10:22:10,059 - root - DEBUG - Data is being inserted into the tables, this might take a while...
2025-03-13 10:22:10,083 - root - INFO - Inserted 4372 rows into customer
2025-03-13 10:22:10,548 - root - INFO - Inserted 24446 rows into invoice
2025-03-13 10:22:10,583 - root - INFO - Inserted 3958 rows into product
2025-03-13 10:22:25,571 - root - INFO - Inserted 529771 rows into invoice_details
2025-03-13 10:22:25,574 - root - INFO - All data committed successfully
2025-03-14 04:08:10,331 - root - DEBUG - Attempting to connect to retail_db
2025-03-14 04:08:10,355 - root - DEBUG - Connected successfully to retail_db
2025-03-14 04:08:11,284 - root - INFO - Dataset read
2025-03-14 04:08:11,558 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-14 04:08:11,617 - root - INFO - Identified 1454 corrupted rows.
2025-03-14 04:08:11,715 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-14 04:08:12,464 - root - INFO - Identified 5268 duplicate rows.
2025-03-14 04:08:12,464 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-14 04:08:12,934 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-14 04:08:12,998 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-14 04:08:13,225 - root - INFO - Inserted 4372 rows into customer
2025-03-14 04:08:13,680 - root - INFO - Inserted 24446 rows into invoice
2025-03-14 04:08:13,712 - root - INFO - Inserted 3958 rows into product
2025-03-14 04:08:28,428 - root - INFO - Inserted 529771 rows into invoice_details
2025-03-14 04:11:54,172 - root - DEBUG - Attempting to connect to retail_db
2025-03-14 04:11:54,195 - root - DEBUG - Connected successfully to retail_db
2025-03-14 04:11:55,248 - root - INFO - Dataset read
2025-03-14 04:11:55,547 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-14 04:11:55,609 - root - INFO - Identified 1454 corrupted rows.
2025-03-14 04:11:55,715 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-14 04:11:56,500 - root - INFO - Identified 5268 duplicate rows.
2025-03-14 04:11:56,500 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-14 04:11:56,971 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-14 04:11:57,036 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-14 04:11:57,266 - root - INFO - Inserted 4372 rows into customer
2025-03-14 04:11:57,719 - root - INFO - Inserted 24446 rows into invoice
2025-03-14 04:11:57,757 - root - INFO - Inserted 3958 rows into product
2025-03-14 04:12:12,739 - root - INFO - Inserted 529771 rows into invoice_details
2025-03-14 04:12:16,081 - root - DEBUG - Attempting to connect to retail_db
2025-03-14 04:12:16,106 - root - DEBUG - Connected successfully to retail_db
2025-03-14 04:12:17,110 - root - INFO - Dataset read
2025-03-14 04:12:17,465 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-14 04:12:17,532 - root - INFO - Identified 1454 corrupted rows.
2025-03-14 04:12:17,640 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-14 04:12:18,465 - root - INFO - Identified 5268 duplicate rows.
2025-03-14 04:12:18,465 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-14 04:12:18,970 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-14 04:12:19,043 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-14 04:12:19,306 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-22 04:22:34,196 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 04:22:34,219 - root - DEBUG - Connected successfully to retail_db
2025-03-22 04:22:35,148 - root - INFO - Dataset read
2025-03-22 04:22:35,414 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-22 04:22:35,471 - root - INFO - Identified 1454 corrupted rows.
2025-03-22 04:22:35,565 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-22 04:22:36,327 - root - INFO - Identified 5268 duplicate rows.
2025-03-22 04:22:36,328 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-22 04:22:36,794 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-22 04:22:36,858 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-22 04:22:37,082 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-22 04:48:17,910 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 04:48:17,933 - root - DEBUG - Connected successfully to postgres
2025-03-22 04:48:17,934 - root - ERROR - Database retail_db already exists
2025-03-22 04:48:17,934 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 04:48:17,956 - root - DEBUG - Connected successfully to retail_db
2025-03-22 04:48:17,956 - root - DEBUG - Executing tables creation query
2025-03-22 04:48:17,957 - root - INFO - Tables created successfully!
2025-03-22 04:48:17,957 - root - DEBUG - Database conncetion closed
2025-03-22 04:51:04,922 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 04:51:04,959 - root - DEBUG - Connected successfully to postgres
2025-03-22 04:51:04,960 - root - ERROR - Database retail_db already exists
2025-03-22 04:51:04,961 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 04:51:04,983 - root - DEBUG - Connected successfully to retail_db
2025-03-22 04:51:04,983 - root - DEBUG - Executing tables creation query
2025-03-22 04:51:04,987 - root - INFO - Tables created successfully!
2025-03-22 04:51:04,988 - root - DEBUG - Database conncetion closed
2025-03-22 04:51:20,053 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 04:51:20,076 - root - DEBUG - Connected successfully to postgres
2025-03-22 04:51:20,077 - root - ERROR - Database retail_db already exists
2025-03-22 04:51:20,078 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 04:51:20,099 - root - DEBUG - Connected successfully to retail_db
2025-03-22 04:51:20,099 - root - DEBUG - Executing tables creation query
2025-03-22 04:51:20,100 - root - INFO - Tables created successfully!
2025-03-22 04:51:20,100 - root - DEBUG - Database conncetion closed
2025-03-22 04:51:20,563 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 04:51:20,585 - root - DEBUG - Connected successfully to retail_db
2025-03-22 04:51:21,507 - root - INFO - Dataset read
2025-03-22 04:51:21,767 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-22 04:51:21,826 - root - INFO - Identified 1454 corrupted rows.
2025-03-22 04:51:21,919 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-22 04:51:22,705 - root - INFO - Identified 5268 duplicate rows.
2025-03-22 04:51:22,705 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-22 04:51:23,177 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-22 04:51:23,240 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-22 04:51:23,458 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-22 05:22:07,134 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:22:07,161 - root - DEBUG - Connected successfully to postgres
2025-03-22 05:22:07,162 - root - ERROR - Database retail_db already exists
2025-03-22 05:22:07,162 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:22:07,184 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:22:07,184 - root - DEBUG - Executing tables creation query
2025-03-22 05:22:07,186 - root - INFO - Tables created successfully!
2025-03-22 05:22:07,187 - root - DEBUG - Database conncetion closed
2025-03-22 05:22:07,633 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:22:07,655 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:22:08,589 - root - INFO - Dataset read
2025-03-22 05:22:08,854 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-22 05:22:08,911 - root - INFO - Identified 1454 corrupted rows.
2025-03-22 05:22:09,005 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-22 05:22:09,757 - root - INFO - Identified 5268 duplicate rows.
2025-03-22 05:22:09,757 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-22 05:22:10,246 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-22 05:22:10,312 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-22 05:22:10,531 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-22 05:22:32,671 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:22:32,695 - root - DEBUG - Connected successfully to postgres
2025-03-22 05:22:32,696 - root - ERROR - Database retail_db already exists
2025-03-22 05:22:32,696 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:22:32,715 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:22:32,715 - root - DEBUG - Executing tables creation query
2025-03-22 05:22:32,716 - root - INFO - Tables created successfully!
2025-03-22 05:22:32,718 - root - DEBUG - Database conncetion closed
2025-03-22 05:22:33,182 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:22:33,208 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:22:34,138 - root - INFO - Dataset read
2025-03-22 05:22:34,399 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-22 05:22:34,457 - root - INFO - Identified 1454 corrupted rows.
2025-03-22 05:22:34,552 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-22 05:22:35,292 - root - INFO - Identified 5268 duplicate rows.
2025-03-22 05:22:35,293 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-22 05:22:35,755 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-22 05:22:35,821 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-22 05:22:36,035 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-22 05:33:47,488 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:33:47,514 - root - DEBUG - Connected successfully to postgres
2025-03-22 05:33:47,515 - root - ERROR - Database retail_db already exists
2025-03-22 05:33:47,516 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:33:47,536 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:33:47,537 - root - DEBUG - Executing tables creation query
2025-03-22 05:33:47,538 - root - INFO - Tables created successfully!
2025-03-22 05:33:47,538 - root - DEBUG - Database conncetion closed
2025-03-22 05:33:47,985 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:33:48,009 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:33:48,910 - root - INFO - Dataset read
2025-03-22 05:33:49,173 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-22 05:33:49,230 - root - INFO - Identified 1454 corrupted rows.
2025-03-22 05:33:49,325 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-22 05:33:50,066 - root - INFO - Identified 5268 duplicate rows.
2025-03-22 05:33:50,066 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-22 05:33:50,534 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-22 05:33:50,596 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-22 05:33:50,817 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-22 05:34:20,680 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:34:20,700 - root - DEBUG - Connected successfully to postgres
2025-03-22 05:34:20,700 - root - ERROR - Database retail_db already exists
2025-03-22 05:34:20,701 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:34:20,717 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:34:20,717 - root - DEBUG - Executing tables creation query
2025-03-22 05:34:20,718 - root - INFO - Tables created successfully!
2025-03-22 05:34:20,718 - root - DEBUG - Database conncetion closed
2025-03-22 05:34:21,169 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:34:21,187 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:34:22,092 - root - INFO - Dataset read
2025-03-22 05:34:22,349 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-22 05:34:22,401 - root - INFO - Identified 1454 corrupted rows.
2025-03-22 05:34:22,493 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-22 05:34:23,225 - root - INFO - Identified 5268 duplicate rows.
2025-03-22 05:34:23,226 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-22 05:34:23,684 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-22 05:34:23,742 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-22 05:34:23,958 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-22 05:36:22,613 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:36:22,635 - root - DEBUG - Connected successfully to postgres
2025-03-22 05:36:22,636 - root - ERROR - Database retail_db already exists
2025-03-22 05:36:22,636 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:36:22,653 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:36:22,653 - root - DEBUG - Executing tables creation query
2025-03-22 05:36:22,654 - root - INFO - Tables created successfully!
2025-03-22 05:36:22,654 - root - DEBUG - Database conncetion closed
2025-03-22 05:36:23,097 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:36:23,112 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:36:24,053 - root - INFO - Dataset read
2025-03-22 05:36:24,334 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-22 05:36:24,398 - root - INFO - Identified 1454 corrupted rows.
2025-03-22 05:36:24,501 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-22 05:36:25,285 - root - INFO - Identified 5268 duplicate rows.
2025-03-22 05:36:25,286 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-22 05:36:25,759 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-22 05:36:25,825 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-22 05:36:26,063 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-22 05:36:33,530 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:36:33,550 - root - DEBUG - Connected successfully to postgres
2025-03-22 05:36:33,553 - root - ERROR - Database retail_db already exists
2025-03-22 05:36:33,553 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:36:33,571 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:36:33,571 - root - DEBUG - Executing tables creation query
2025-03-22 05:36:33,572 - root - INFO - Tables created successfully!
2025-03-22 05:36:33,573 - root - DEBUG - Database conncetion closed
2025-03-22 05:36:34,021 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:36:34,044 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:36:34,962 - root - INFO - Dataset read
2025-03-22 05:36:35,227 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-22 05:36:35,285 - root - INFO - Identified 1454 corrupted rows.
2025-03-22 05:36:35,378 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-22 05:36:36,123 - root - INFO - Identified 5268 duplicate rows.
2025-03-22 05:36:36,123 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-22 05:36:36,590 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-22 05:36:36,652 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-22 05:36:36,869 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-22 05:36:41,008 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:36:41,028 - root - DEBUG - Connected successfully to postgres
2025-03-22 05:36:41,030 - root - ERROR - Database retail_db already exists
2025-03-22 05:36:41,030 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:36:41,048 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:36:41,049 - root - DEBUG - Executing tables creation query
2025-03-22 05:36:41,049 - root - INFO - Tables created successfully!
2025-03-22 05:36:41,050 - root - DEBUG - Database conncetion closed
2025-03-22 05:36:41,485 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:36:41,508 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:36:42,411 - root - INFO - Dataset read
2025-03-22 05:36:42,670 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-22 05:36:42,725 - root - INFO - Identified 1454 corrupted rows.
2025-03-22 05:36:42,824 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-22 05:36:43,555 - root - INFO - Identified 5268 duplicate rows.
2025-03-22 05:36:43,555 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-22 05:36:44,027 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-22 05:36:44,088 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-22 05:36:44,299 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-22 05:37:19,948 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:37:19,969 - root - DEBUG - Connected successfully to postgres
2025-03-22 05:37:19,970 - root - ERROR - Database retail_db already exists
2025-03-22 05:37:19,970 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:37:19,987 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:37:19,988 - root - DEBUG - Executing tables creation query
2025-03-22 05:37:19,988 - root - INFO - Tables created successfully!
2025-03-22 05:37:19,989 - root - DEBUG - Database conncetion closed
2025-03-22 05:37:27,442 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:37:27,461 - root - DEBUG - Connected successfully to postgres
2025-03-22 05:37:27,462 - root - ERROR - Database retail_db already exists
2025-03-22 05:37:27,462 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:37:27,480 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:37:27,480 - root - DEBUG - Executing tables creation query
2025-03-22 05:37:27,482 - root - INFO - Tables created successfully!
2025-03-22 05:37:27,482 - root - DEBUG - Database conncetion closed
2025-03-22 05:37:27,923 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:37:27,943 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:37:28,852 - root - INFO - Dataset read
2025-03-22 05:37:29,110 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-22 05:37:29,162 - root - INFO - Identified 1454 corrupted rows.
2025-03-22 05:37:29,255 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-22 05:37:29,992 - root - INFO - Identified 5268 duplicate rows.
2025-03-22 05:37:29,992 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-22 05:37:30,451 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-22 05:37:30,508 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-22 05:37:30,715 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-22 05:38:24,847 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:38:24,866 - root - DEBUG - Connected successfully to postgres
2025-03-22 05:38:24,867 - root - ERROR - Database retail_db already exists
2025-03-22 05:38:24,867 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:38:24,884 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:38:24,884 - root - DEBUG - Executing tables creation query
2025-03-22 05:38:24,885 - root - INFO - Tables created successfully!
2025-03-22 05:38:24,886 - root - DEBUG - Database conncetion closed
2025-03-22 05:38:25,349 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:38:25,367 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:38:26,284 - root - INFO - Dataset read
2025-03-22 05:38:26,543 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-22 05:38:26,598 - root - INFO - Identified 1454 corrupted rows.
2025-03-22 05:38:26,690 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-22 05:38:27,439 - root - INFO - Identified 5268 duplicate rows.
2025-03-22 05:38:27,440 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-22 05:38:27,908 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-22 05:38:27,966 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-22 05:38:28,175 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-22 05:38:36,913 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:38:36,932 - root - DEBUG - Connected successfully to postgres
2025-03-22 05:38:36,933 - root - ERROR - Database retail_db already exists
2025-03-22 05:38:36,934 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:38:36,951 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:38:36,951 - root - DEBUG - Executing tables creation query
2025-03-22 05:38:36,951 - root - INFO - Tables created successfully!
2025-03-22 05:38:36,952 - root - DEBUG - Database conncetion closed
2025-03-22 05:38:37,395 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:38:37,413 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:38:38,334 - root - INFO - Dataset read
2025-03-22 05:38:38,590 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-22 05:38:38,643 - root - INFO - Identified 1454 corrupted rows.
2025-03-22 05:38:38,735 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-22 05:38:39,525 - root - INFO - Identified 5268 duplicate rows.
2025-03-22 05:38:39,526 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-22 05:38:39,996 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-22 05:38:40,061 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-22 05:38:40,278 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-22 05:39:00,094 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:39:00,111 - root - DEBUG - Connected successfully to postgres
2025-03-22 05:39:00,112 - root - ERROR - Database retail_db already exists
2025-03-22 05:39:00,112 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:39:00,131 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:39:00,131 - root - DEBUG - Executing tables creation query
2025-03-22 05:39:00,132 - root - INFO - Tables created successfully!
2025-03-22 05:39:00,132 - root - DEBUG - Database conncetion closed
2025-03-22 05:39:00,581 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:39:00,600 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:39:01,529 - root - INFO - Dataset read
2025-03-22 05:39:01,791 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-22 05:39:01,850 - root - INFO - Identified 1454 corrupted rows.
2025-03-22 05:39:01,940 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-22 05:39:02,675 - root - INFO - Identified 5268 duplicate rows.
2025-03-22 05:39:02,675 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-22 05:39:03,141 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-22 05:39:03,200 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-22 05:39:03,407 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-22 05:42:39,343 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:42:39,364 - root - DEBUG - Connected successfully to postgres
2025-03-22 05:42:39,400 - root - INFO - Database retail_db created!
2025-03-22 05:42:39,400 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:42:39,420 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:42:39,420 - root - DEBUG - Executing tables creation query
2025-03-22 05:42:39,441 - root - INFO - Tables created successfully!
2025-03-22 05:42:39,441 - root - DEBUG - Database conncetion closed
2025-03-22 05:42:39,890 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:42:39,906 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:42:40,856 - root - INFO - Dataset read
2025-03-22 05:42:41,124 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-22 05:42:41,179 - root - INFO - Identified 1454 corrupted rows.
2025-03-22 05:42:41,272 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-22 05:42:42,041 - root - INFO - Identified 5268 duplicate rows.
2025-03-22 05:42:42,041 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-22 05:42:42,503 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-22 05:42:42,562 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-22 05:42:42,777 - root - INFO - Inserted 4372 rows into customer
2025-03-22 05:42:43,216 - root - INFO - Inserted 24446 rows into invoice
2025-03-22 05:42:43,245 - root - INFO - Inserted 3958 rows into product
2025-03-22 05:42:57,679 - root - INFO - Inserted 529771 rows into invoice_details
2025-03-22 05:49:17,320 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:49:17,340 - root - DEBUG - Connected successfully to postgres
2025-03-22 05:49:17,341 - root - ERROR - Database retail_db already exists
2025-03-22 05:49:17,341 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:49:17,359 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:49:17,359 - root - DEBUG - Executing tables creation query
2025-03-22 05:49:17,360 - root - INFO - Tables created successfully!
2025-03-22 05:49:17,360 - root - DEBUG - Database conncetion closed
2025-03-22 05:49:17,796 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:49:17,819 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:49:18,727 - root - INFO - Dataset read
2025-03-22 05:49:18,989 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-22 05:49:19,043 - root - INFO - Identified 1454 corrupted rows.
2025-03-22 05:49:19,139 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-22 05:49:19,872 - root - INFO - Identified 5268 duplicate rows.
2025-03-22 05:49:19,872 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-22 05:49:20,354 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-22 05:49:20,411 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-22 05:49:20,618 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-22 05:49:22,107 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:49:22,129 - root - DEBUG - Connected successfully to postgres
2025-03-22 05:49:22,130 - root - ERROR - Database retail_db already exists
2025-03-22 05:49:22,130 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:49:22,147 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:49:22,147 - root - DEBUG - Executing tables creation query
2025-03-22 05:49:22,148 - root - INFO - Tables created successfully!
2025-03-22 05:49:22,148 - root - DEBUG - Database conncetion closed
2025-03-22 05:49:22,581 - root - DEBUG - Attempting to connect to retail_db
2025-03-22 05:49:22,597 - root - DEBUG - Connected successfully to retail_db
2025-03-22 05:49:23,508 - root - INFO - Dataset read
2025-03-22 05:49:23,766 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-22 05:49:23,822 - root - INFO - Identified 1454 corrupted rows.
2025-03-22 05:49:23,914 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-22 05:49:24,654 - root - INFO - Identified 5268 duplicate rows.
2025-03-22 05:49:24,654 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-22 05:49:25,137 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-22 05:49:25,195 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-22 05:49:25,403 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-23 08:26:30,579 - root - DEBUG - Attempting to connect to postgres
2025-03-23 08:26:30,580 - root - ERROR - Connection error: invalid dsn: invalid connection option "passwrod"

2025-03-23 08:26:46,575 - root - DEBUG - Attempting to connect to postgres
2025-03-23 08:26:46,601 - root - DEBUG - Connected successfully to postgres
2025-03-23 08:26:46,603 - root - ERROR - Database postgres already exists
2025-03-23 08:26:46,603 - root - DEBUG - Attempting to connect to postgres
2025-03-23 08:26:46,644 - root - DEBUG - Connected successfully to postgres
2025-03-23 08:26:46,644 - root - DEBUG - Executing tables creation query
2025-03-23 08:26:46,697 - root - INFO - Tables created successfully!
2025-03-23 08:26:46,698 - root - DEBUG - Database conncetion closed
2025-03-23 08:27:05,410 - root - DEBUG - Attempting to connect to postgres
2025-03-23 08:27:05,431 - root - DEBUG - Connected successfully to postgres
2025-03-23 08:27:06,542 - root - INFO - Dataset read
2025-03-23 08:27:06,824 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-23 08:27:06,887 - root - INFO - Identified 1454 corrupted rows.
2025-03-23 08:27:06,992 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-23 08:27:07,778 - root - INFO - Identified 5268 duplicate rows.
2025-03-23 08:27:07,779 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-23 08:27:08,354 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-23 08:27:08,429 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-23 08:27:08,711 - root - INFO - Inserted 4372 rows into customer
2025-03-23 08:27:09,177 - root - INFO - Inserted 24446 rows into invoice
2025-03-23 08:27:09,208 - root - INFO - Inserted 3958 rows into product
2025-03-23 08:27:24,210 - root - INFO - Inserted 529771 rows into invoice_details
2025-03-23 08:27:32,521 - root - DEBUG - Attempting to connect to postgres
2025-03-23 08:27:32,557 - root - ERROR - Connection error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "vboxuser"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "vboxuser"

2025-03-23 08:36:22,056 - root - DEBUG - Attempting to connect to postgres
2025-03-23 08:36:22,107 - root - DEBUG - Connected successfully to postgres
2025-03-23 08:36:22,109 - root - ERROR - Database postgres already exists
2025-03-23 08:36:22,111 - root - DEBUG - Attempting to connect to postgres
2025-03-23 08:36:22,145 - root - DEBUG - Connected successfully to postgres
2025-03-23 08:36:22,146 - root - DEBUG - Executing tables creation query
2025-03-23 08:36:22,146 - root - INFO - Tables created successfully!
2025-03-23 08:36:22,148 - root - DEBUG - Database conncetion closed
2025-03-23 08:36:26,342 - root - DEBUG - Attempting to connect to postgres
2025-03-23 08:36:26,374 - root - ERROR - Connection error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "vboxuser"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "vboxuser"

2025-03-25 09:10:12,445 - root - DEBUG - Attempting to connect to postgres
2025-03-25 09:10:12,480 - root - ERROR - Connection error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "vboxuser"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "vboxuser"

2025-03-25 09:49:09,479 - root - DEBUG - Attempting to connect to postgres
2025-03-25 09:49:09,500 - root - DEBUG - Connected successfully to postgres
2025-03-25 09:49:09,501 - root - ERROR - Database postgres already exists
2025-03-25 09:49:09,502 - root - DEBUG - Attempting to connect to postgres
2025-03-25 09:49:09,518 - root - DEBUG - Connected successfully to postgres
2025-03-25 09:49:09,518 - root - DEBUG - Executing tables creation query
2025-03-25 09:49:09,519 - root - INFO - Tables created successfully!
2025-03-25 09:49:09,520 - root - DEBUG - Database conncetion closed
2025-03-25 09:49:10,012 - root - DEBUG - Attempting to connect to postgres
2025-03-25 09:49:10,034 - root - DEBUG - Connected successfully to postgres
2025-03-25 09:49:10,976 - root - INFO - Dataset read
2025-03-25 09:49:11,237 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-25 09:49:11,289 - root - INFO - Identified 1454 corrupted rows.
2025-03-25 09:49:11,384 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-25 09:49:12,140 - root - INFO - Identified 5268 duplicate rows.
2025-03-25 09:49:12,140 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-25 09:49:12,605 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-25 09:49:12,666 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-25 09:49:12,875 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-25 09:52:02,448 - root - DEBUG - Attempting to connect to postgres
2025-03-25 09:52:02,469 - root - DEBUG - Connected successfully to postgres
2025-03-25 09:52:02,470 - root - ERROR - Database postgres already exists
2025-03-25 09:52:02,471 - root - DEBUG - Attempting to connect to postgres
2025-03-25 09:52:02,488 - root - DEBUG - Connected successfully to postgres
2025-03-25 09:52:02,489 - root - DEBUG - Executing tables creation query
2025-03-25 09:52:02,490 - root - INFO - Tables created successfully!
2025-03-25 09:52:02,490 - root - DEBUG - Database conncetion closed
2025-03-25 09:52:02,976 - root - DEBUG - Attempting to connect to postgres
2025-03-25 09:52:02,995 - root - DEBUG - Connected successfully to postgres
2025-03-25 09:52:03,934 - root - INFO - Dataset read
2025-03-25 09:52:04,212 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-25 09:52:04,268 - root - INFO - Identified 1454 corrupted rows.
2025-03-25 09:52:04,369 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-25 09:52:05,168 - root - INFO - Identified 5268 duplicate rows.
2025-03-25 09:52:05,169 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-25 09:52:05,682 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-25 09:52:05,741 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-25 09:52:05,966 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-25 09:53:48,033 - root - DEBUG - Attempting to connect to postgres
2025-03-25 09:53:48,052 - root - DEBUG - Connected successfully to postgres
2025-03-25 09:53:48,053 - root - ERROR - Database postgres already exists
2025-03-25 09:53:48,053 - root - DEBUG - Attempting to connect to postgres
2025-03-25 09:53:48,070 - root - DEBUG - Connected successfully to postgres
2025-03-25 09:53:48,070 - root - DEBUG - Executing tables creation query
2025-03-25 09:53:48,071 - root - INFO - Tables created successfully!
2025-03-25 09:53:48,071 - root - DEBUG - Database conncetion closed
2025-03-25 09:53:48,512 - root - DEBUG - Attempting to connect to postgres
2025-03-25 09:53:48,531 - root - DEBUG - Connected successfully to postgres
2025-03-25 09:53:49,428 - root - INFO - Dataset read
2025-03-25 09:53:49,699 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-25 09:53:49,751 - root - INFO - Identified 1454 corrupted rows.
2025-03-25 09:53:49,841 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-25 09:53:50,561 - root - INFO - Identified 5268 duplicate rows.
2025-03-25 09:53:50,561 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-25 09:53:51,022 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-25 09:53:51,079 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-25 09:53:51,285 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-25 09:54:02,112 - root - DEBUG - Attempting to connect to postgres
2025-03-25 09:54:02,150 - root - DEBUG - Connected successfully to postgres
2025-03-25 09:54:03,156 - root - INFO - Dataset read
2025-03-25 09:54:03,421 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-25 09:54:03,486 - root - INFO - Identified 1454 corrupted rows.
2025-03-25 09:54:03,593 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-25 09:54:04,352 - root - INFO - Identified 5268 duplicate rows.
2025-03-25 09:54:04,353 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-25 09:54:04,844 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-25 09:54:04,908 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-25 09:54:05,131 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-25 09:54:42,381 - root - DEBUG - Attempting to connect to postgres
2025-03-25 09:54:42,418 - root - DEBUG - Connected successfully to postgres
2025-03-25 09:54:43,554 - root - INFO - Dataset read
2025-03-25 09:54:43,891 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-25 09:54:43,955 - root - INFO - Identified 1454 corrupted rows.
2025-03-25 09:54:44,076 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-25 09:54:45,094 - root - INFO - Identified 5268 duplicate rows.
2025-03-25 09:54:45,094 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-25 09:54:45,619 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-25 09:54:45,689 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-25 09:54:45,910 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-25 09:59:26,181 - root - DEBUG - Attempting to connect to postgres
2025-03-25 09:59:26,200 - root - DEBUG - Connected successfully to postgres
2025-03-25 09:59:26,201 - root - ERROR - Database postgres already exists
2025-03-25 09:59:26,201 - root - DEBUG - Attempting to connect to postgres
2025-03-25 09:59:26,221 - root - DEBUG - Connected successfully to postgres
2025-03-25 09:59:26,221 - root - DEBUG - Executing tables creation query
2025-03-25 09:59:26,222 - root - INFO - Tables created successfully!
2025-03-25 09:59:26,222 - root - DEBUG - Database conncetion closed
2025-03-25 09:59:26,707 - root - DEBUG - Attempting to connect to postgres
2025-03-25 09:59:26,726 - root - DEBUG - Connected successfully to postgres
2025-03-25 09:59:27,654 - root - INFO - Dataset read
2025-03-25 09:59:27,912 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-25 09:59:27,966 - root - INFO - Identified 1454 corrupted rows.
2025-03-25 09:59:28,067 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-25 09:59:28,833 - root - INFO - Identified 5268 duplicate rows.
2025-03-25 09:59:28,833 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-25 09:59:29,292 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-25 09:59:29,349 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-25 09:59:29,564 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-25 10:03:00,378 - root - DEBUG - Attempting to connect to postgres
2025-03-25 10:03:00,404 - root - DEBUG - Connected successfully to postgres
2025-03-25 10:03:00,406 - root - ERROR - Database postgres already exists
2025-03-25 10:03:00,406 - root - DEBUG - Attempting to connect to postgres
2025-03-25 10:03:00,426 - root - DEBUG - Connected successfully to postgres
2025-03-25 10:03:00,426 - root - DEBUG - Executing tables creation query
2025-03-25 10:03:00,428 - root - INFO - Tables created successfully!
2025-03-25 10:03:00,429 - root - DEBUG - Database conncetion closed
2025-03-25 10:03:36,648 - root - DEBUG - Attempting to connect to postgres
2025-03-25 10:03:36,676 - root - DEBUG - Connected successfully to postgres
2025-03-25 10:03:36,678 - root - ERROR - Database postgres already exists
2025-03-25 10:03:36,683 - root - DEBUG - Attempting to connect to postgres
2025-03-25 10:03:36,711 - root - DEBUG - Connected successfully to postgres
2025-03-25 10:03:36,713 - root - DEBUG - Executing tables creation query
2025-03-25 10:03:36,714 - root - INFO - Tables created successfully!
2025-03-25 10:03:36,715 - root - DEBUG - Database conncetion closed
2025-03-25 10:04:29,928 - root - DEBUG - Attempting to connect to postgres
2025-03-25 10:04:29,951 - root - DEBUG - Connected successfully to postgres
2025-03-25 10:04:30,954 - root - INFO - Dataset read
2025-03-25 10:04:31,265 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-25 10:04:31,326 - root - INFO - Identified 1454 corrupted rows.
2025-03-25 10:04:31,432 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-25 10:04:32,289 - root - INFO - Identified 5268 duplicate rows.
2025-03-25 10:04:32,290 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-25 10:04:32,825 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-25 10:04:32,897 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-25 10:04:33,140 - root - ERROR - Unexpected Error: duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customerid)=(17850) already exists.
CONTEXT:  COPY customer, line 1

2025-03-25 10:06:36,122 - root - DEBUG - Attempting to connect to postgres
2025-03-25 10:06:36,156 - root - DEBUG - Connected successfully to postgres
2025-03-25 10:06:36,158 - root - ERROR - Database postgres already exists
2025-03-25 10:06:36,159 - root - DEBUG - Attempting to connect to postgres
2025-03-25 10:06:36,186 - root - DEBUG - Connected successfully to postgres
2025-03-25 10:06:36,186 - root - DEBUG - Executing tables creation query
2025-03-25 10:06:36,188 - root - INFO - Tables created successfully!
2025-03-25 10:06:36,189 - root - DEBUG - Database conncetion closed
2025-03-25 10:08:10,726 - root - DEBUG - Attempting to connect to retail_db
2025-03-25 10:08:10,759 - root - DEBUG - Connected successfully to postgres
2025-03-25 10:08:10,804 - root - INFO - Database retail_db created!
2025-03-25 10:08:10,805 - root - DEBUG - Attempting to connect to retail_db
2025-03-25 10:08:10,837 - root - DEBUG - Connected successfully to retail_db
2025-03-25 10:08:10,838 - root - DEBUG - Executing tables creation query
2025-03-25 10:08:10,857 - root - INFO - Tables created successfully!
2025-03-25 10:08:10,858 - root - DEBUG - Database conncetion closed
2025-03-25 10:08:15,421 - root - DEBUG - Attempting to connect to retail_db
2025-03-25 10:08:15,456 - root - DEBUG - Connected successfully to retail_db
2025-03-25 10:08:16,726 - root - INFO - Dataset read
2025-03-25 10:08:17,007 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-25 10:08:17,064 - root - INFO - Identified 1454 corrupted rows.
2025-03-25 10:08:17,171 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-25 10:08:17,984 - root - INFO - Identified 5268 duplicate rows.
2025-03-25 10:08:17,984 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-25 10:08:18,466 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-25 10:08:18,539 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-25 10:08:18,780 - root - INFO - Inserted 4372 rows into customer
2025-03-25 10:08:19,223 - root - INFO - Inserted 24446 rows into invoice
2025-03-25 10:08:19,264 - root - INFO - Inserted 3958 rows into product
2025-03-25 10:08:34,668 - root - INFO - Inserted 529771 rows into invoice_details
2025-03-25 10:09:19,866 - root - DEBUG - Attempting to connect to retail_db
2025-03-25 10:09:19,886 - root - DEBUG - Connected successfully to postgres
2025-03-25 10:09:19,924 - root - INFO - Database retail_db created!
2025-03-25 10:09:19,925 - root - DEBUG - Attempting to connect to retail_db
2025-03-25 10:09:19,944 - root - DEBUG - Connected successfully to retail_db
2025-03-25 10:09:19,944 - root - DEBUG - Executing tables creation query
2025-03-25 10:09:19,965 - root - INFO - Tables created successfully!
2025-03-25 10:09:19,966 - root - DEBUG - Database conncetion closed
2025-03-25 10:09:20,412 - root - DEBUG - Attempting to connect to retail_db
2025-03-25 10:09:20,439 - root - DEBUG - Connected successfully to retail_db
2025-03-25 10:09:21,340 - root - INFO - Dataset read
2025-03-25 10:09:21,605 - root - INFO - Missing values per column:
InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64.
2025-03-25 10:09:21,662 - root - INFO - Identified 1454 corrupted rows.
2025-03-25 10:09:21,753 - root - INFO - corrupted rows removed, New dataset size is (540455, 8).
2025-03-25 10:09:22,487 - root - INFO - Identified 5268 duplicate rows.
2025-03-25 10:09:22,487 - root - INFO - duplicate rows removed, New dataset size is (535187, 8).
2025-03-25 10:09:22,969 - root - INFO - Converted 'InvoiceDate' to datetime and 'Country' to string.
2025-03-25 10:09:23,026 - root - INFO - Dataset successfully partitioned into Data frames.
2025-03-25 10:09:23,246 - root - INFO - Inserted 4372 rows into customer
2025-03-25 10:09:23,695 - root - INFO - Inserted 24446 rows into invoice
2025-03-25 10:09:23,723 - root - INFO - Inserted 3958 rows into product
2025-03-25 10:09:38,578 - root - INFO - Inserted 529771 rows into invoice_details
